schema_version: 1.0.0
id: azure-builtin.azure.apimanagement.service.api-management-should-disable-public-network-access-to-the-service-configuration-endpo
version: 1.0.1
source: azure_policy
severity: medium
category: security
resource_type: azure.apimanagement.service
check_logic:
  kind: expression
  reference: azure-policy://df73bd95-24da-4a4f-96b9-4e8b94b402bd
remediation:
  template_ref: remediation/azure-builtin/df73bd95-24da-4a4f-96b9-4e8b94b402bd.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: df73bd95-24da-4a4f-96b9-4e8b94b402bd
  azure_policy_display_name: API Management should disable public network access to
    the service configuration endpoints
  azure_policy_effect_default: AuditIfNotExists
  azure_policy_category: API Management
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/API
    Management/PublicEndpoint_AINE.json
  source_version: 1.0.1
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
