schema_version: 1.0.0
id: compliance.guest-configuration.preview-deploy-prerequisites-to-e
title: '(Azure Initiative) [Preview]: Deploy prerequisites to enable Guest Configuration
  policies on virtual machines using user-assigned managed identity'
description: This initiative adds a user-assigned managed identity and deploys the
  platform-appropriate Guest Configuration extension to virtual machines that are
  eligible to be monitored by Guest Configuration policies. This is a prerequisite
  for all Guest Configuration policies and must be assigned to the policy assignment
  scope before using any Guest Configuration policy. For more information on Guest
  Configuration, visit https://aka.ms/gcpol.
provenance:
  authored_by: azure-policy-initiative-collector
  based_on:
  - azure-policy://UserAssignedIdentity_Prerequisites
  review_cadence_days: 90
rules:
- id: azure-builtin.compute.vm.preview-add-user-assigned-managed-identity-to-enable-guest-configuration-assignments-on-virtual-mach
  mode: shadow
- id: azure-builtin.compute.vm.deploy-the-windows-guest-configuration-extension-to-enable-guest-configuration-assignments-on-window
  mode: shadow
- id: azure-builtin.compute.vm.deploy-the-linux-guest-configuration-extension-to-enable-guest-configuration-assignments-on-linux-vm
  mode: shadow
