#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
environment_file="${1:-}"
approval_ref="${SCENARIO_LAB_APPROVAL_REF:-}"
scenario_id="${SCENARIO_LAB_SCENARIO_ID:-all}"

if [[ -z "$environment_file" || ! -f "$environment_file" ]]; then
  echo "run-reference-sweep: a prepared environment file is required." >&2
  exit 2
fi
if [[ "$(stat -c '%a' "$environment_file")" != "600" ]]; then
  echo "run-reference-sweep: the prepared environment file must use mode 600." >&2
  exit 1
fi
if [[ "${SCENARIO_LAB_CONFIRM_ENFORCE:-}" != "true" ]]; then
  echo "run-reference-sweep: SCENARIO_LAB_CONFIRM_ENFORCE=true is required." >&2
  exit 2
fi
if [[ -z "$approval_ref" || ${#approval_ref} -gt 256 ]]; then
  echo "run-reference-sweep: a bounded SCENARIO_LAB_APPROVAL_REF is required." >&2
  exit 2
fi
case "$scenario_id" in
  all|aks-pod-kill|aks-pod-cpu-spike|aks-http-abort|vm-cpu-stress|vm-mem-stress|aks-bad-deploy|aoai-tpm-throttle|mysql-cpu-pressure|appgw-backend-failure|network-rtt-delay) ;;
  *)
    echo "run-reference-sweep: SCENARIO_LAB_SCENARIO_ID is not allowlisted." >&2
    exit 2
    ;;
esac

# The file is generated by prepare-runner.sh from constrained Terraform outputs.
# shellcheck disable=SC1090
source "$environment_file"
export FDAI_ENFORCE_APPROVAL_REF="$approval_ref"

cd "$repo_root"
if [[ "$scenario_id" == "all" ]]; then
  scenario_args=(--run-sweep)
else
  scenario_args=(--run "$scenario_id")
fi

# The deployment's evidence projection reads the measured report from this root,
# so pin it when the caller supplies one. Only measured runs produce the file.
report_root="${FDAI_ENFORCE_REPORT_ROOT:-}"
if [[ -n "$report_root" ]]; then
  mkdir -p -- "$report_root"
  scenario_args+=(--measured-report "$report_root/report.json")
fi

# The reference sweep runs only through the governed chaos adapter; the runner
# refuses before substrate access when promotion, approval, or the deployment
# provider is absent.
uv run python scripts/catalog/run-catalog-scenario.py "${scenario_args[@]}" --confirm-enforce
