#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
environment_file="${1:-}"
approval_ref="${SCENARIO_LAB_APPROVAL_REF:-}"
scenario_id="${SCENARIO_LAB_SCENARIO_ID:-all}"

if [[ -z "$environment_file" || ! -f "$environment_file" ]]; then
  echo "run-reference-sweep: a prepared environment file is required." >&2
  exit 2
fi
if [[ "$(stat -c '%a' "$environment_file")" != "600" ]]; then
  echo "run-reference-sweep: the prepared environment file must use mode 600." >&2
  exit 1
fi
if [[ "${SCENARIO_LAB_CONFIRM_ENFORCE:-}" != "true" ]]; then
  echo "run-reference-sweep: SCENARIO_LAB_CONFIRM_ENFORCE=true is required." >&2
  exit 2
fi
if [[ -z "$approval_ref" || ${#approval_ref} -gt 256 ]]; then
  echo "run-reference-sweep: a bounded SCENARIO_LAB_APPROVAL_REF is required." >&2
  exit 2
fi
case "$scenario_id" in
  all|aks-pod-kill|aks-pod-cpu-spike|aks-http-abort|vm-cpu-stress|vm-mem-stress|aks-bad-deploy|aoai-tpm-throttle|mysql-cpu-pressure|appgw-backend-failure|network-rtt-delay) ;;
  *)
    echo "run-reference-sweep: SCENARIO_LAB_SCENARIO_ID is not allowlisted." >&2
    exit 2
    ;;
esac

# The file is generated by prepare-runner.sh from constrained Terraform outputs.
# shellcheck disable=SC1090
source "$environment_file"
export FDAI_ENFORCE_APPROVAL_REF="$approval_ref"

cd "$repo_root"
scenario_args=()
if [[ "$scenario_id" != "all" ]]; then
  scenario_args+=("$scenario_id")
fi
uv run python scripts/catalog/run-enforce-scenarios.py "${scenario_args[@]}"
