#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
environment_file="${1:-}"
approval_ref="${SCENARIO_LAB_APPROVAL_REF:-}"

if [[ -z "$environment_file" || ! -f "$environment_file" ]]; then
  echo "run-reference-sweep: a prepared environment file is required." >&2
  exit 2
fi
if [[ "$(stat -c '%a' "$environment_file")" != "600" ]]; then
  echo "run-reference-sweep: the prepared environment file must use mode 600." >&2
  exit 1
fi
if [[ "${SCENARIO_LAB_CONFIRM_ENFORCE:-}" != "true" ]]; then
  echo "run-reference-sweep: SCENARIO_LAB_CONFIRM_ENFORCE=true is required." >&2
  exit 2
fi
if [[ -z "$approval_ref" || ${#approval_ref} -gt 256 ]]; then
  echo "run-reference-sweep: a bounded SCENARIO_LAB_APPROVAL_REF is required." >&2
  exit 2
fi

# The file is generated by prepare-runner.sh from constrained Terraform outputs.
# shellcheck disable=SC1090
source "$environment_file"
export FDAI_ENFORCE_APPROVAL_REF="$approval_ref"

cd "$repo_root"
uv run python scripts/catalog/run-enforce-scenarios.py
