"""Synthetic customer-agnostic inventory graph for local console development."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from fdai.delivery.read_api.routes.inventory_graph import InventoryGraphViewNotFoundError

_FDAI_RESOURCES: tuple[dict[str, Any], ...] = (
    {
        "id": "sub-example",
        "type": "subscription",
        "name": "Production subscription",
        "status": "healthy",
        "x": 0.35,
        "y": 0.35,
        "w": 17.3,
        "h": 11.3,
    },
    {
        "id": "rg-network",
        "type": "resource-group",
        "name": "rg-network",
        "status": "healthy",
        "parent_id": "sub-example",
        "x": 0.9,
        "y": 1.25,
        "w": 6.2,
        "h": 9.5,
    },
    {
        "id": "rg-app",
        "type": "resource-group",
        "name": "rg-app",
        "status": "healthy",
        "parent_id": "sub-example",
        "x": 7.4,
        "y": 1.25,
        "w": 5.2,
        "h": 9.5,
    },
    {
        "id": "rg-data",
        "type": "resource-group",
        "name": "rg-data",
        "status": "healthy",
        "parent_id": "sub-example",
        "x": 12.9,
        "y": 1.25,
        "w": 4.2,
        "h": 9.5,
    },
    {
        "id": "vnet-hub",
        "type": "virtual-network",
        "name": "vnet-hub",
        "status": "healthy",
        "parent_id": "rg-network",
        "x": 1.35,
        "y": 2.15,
        "w": 5.25,
        "h": 7.8,
    },
    {
        "id": "snet-ingress",
        "type": "subnet",
        "name": "snet-ingress",
        "status": "healthy",
        "parent_id": "vnet-hub",
        "x": 1.75,
        "y": 2.85,
        "w": 4.45,
        "h": 2.45,
    },
    {
        "id": "snet-private",
        "type": "subnet",
        "name": "snet-private",
        "status": "healthy",
        "parent_id": "vnet-hub",
        "x": 1.75,
        "y": 5.75,
        "w": 4.45,
        "h": 3.6,
    },
    {
        "id": "fd-prod",
        "type": "front-door",
        "name": "fd-prod",
        "status": "healthy",
        "parent_id": "sub-example",
        "x": 1.0,
        "y": 1.0,
    },
    {
        "id": "agw-prod",
        "type": "application-gateway",
        "name": "agw-prod",
        "status": "healthy",
        "parent_id": "snet-ingress",
        "x": 2.35,
        "y": 3.55,
    },
    {
        "id": "lb-internal",
        "type": "load-balancer",
        "name": "lb-internal",
        "status": "healthy",
        "parent_id": "snet-ingress",
        "x": 4.75,
        "y": 4.0,
    },
    {
        "id": "fw-hub",
        "type": "firewall",
        "name": "fw-hub",
        "status": "healthy",
        "parent_id": "snet-private",
        "x": 2.45,
        "y": 7.0,
    },
    {
        "id": "web-api",
        "type": "app-service",
        "name": "web-api",
        "status": "healthy",
        "parent_id": "rg-app",
        "x": 8.45,
        "y": 3.0,
    },
    {
        "id": "event-worker",
        "type": "container-app",
        "name": "event-worker",
        "status": "healthy",
        "parent_id": "rg-app",
        "x": 10.65,
        "y": 3.9,
    },
    {
        "id": "event-hub",
        "type": "event-hub",
        "name": "event-hub",
        "status": "healthy",
        "parent_id": "rg-app",
        "x": 10.55,
        "y": 5.65,
    },
    {
        "id": "scheduler",
        "type": "function-app",
        "name": "scheduler",
        "status": "warning",
        "parent_id": "rg-app",
        "x": 8.65,
        "y": 6.1,
    },
    {
        "id": "aks-ops",
        "type": "aks-cluster",
        "name": "aks-ops",
        "status": "healthy",
        "parent_id": "rg-app",
        "x": 10.6,
        "y": 7.55,
    },
    {
        "id": "kv-prod",
        "type": "key-vault",
        "name": "kv-prod",
        "status": "healthy",
        "parent_id": "rg-app",
        "x": 8.35,
        "y": 9.0,
    },
    {
        "id": "pg-prod",
        "type": "postgresql",
        "name": "pg-prod",
        "status": "healthy",
        "parent_id": "rg-data",
        "x": 13.65,
        "y": 3.15,
    },
    {
        "id": "redis-prod",
        "type": "redis",
        "name": "redis-prod",
        "status": "healthy",
        "parent_id": "rg-data",
        "x": 15.45,
        "y": 5.35,
    },
    {
        "id": "stprod",
        "type": "storage-account",
        "name": "stprod",
        "status": "healthy",
        "parent_id": "rg-data",
        "x": 13.8,
        "y": 7.8,
    },
)

_FDAI_LINKS: tuple[dict[str, str], ...] = (
    {"source": "sub-example", "target": "rg-network", "type": "contains"},
    {"source": "sub-example", "target": "rg-app", "type": "contains"},
    {"source": "sub-example", "target": "rg-data", "type": "contains"},
    {"source": "rg-network", "target": "vnet-hub", "type": "contains"},
    {"source": "vnet-hub", "target": "snet-ingress", "type": "contains"},
    {"source": "vnet-hub", "target": "snet-private", "type": "contains"},
    {"source": "fd-prod", "target": "agw-prod", "type": "depends_on"},
    {"source": "agw-prod", "target": "lb-internal", "type": "depends_on"},
    {"source": "lb-internal", "target": "web-api", "type": "depends_on"},
    {"source": "web-api", "target": "event-hub", "type": "depends_on"},
    {"source": "event-hub", "target": "event-worker", "type": "depends_on"},
    {"source": "web-api", "target": "pg-prod", "type": "depends_on"},
    {"source": "web-api", "target": "redis-prod", "type": "depends_on"},
    {"source": "event-worker", "target": "stprod", "type": "attached_to"},
    {"source": "aks-ops", "target": "kv-prod", "type": "attached_to"},
)

_COMMERCE_RESOURCES: tuple[dict[str, Any], ...] = (
    {
        "id": "sub-commerce",
        "type": "subscription",
        "name": "Commerce subscription",
        "status": "healthy",
        "x": 0.35,
        "y": 0.35,
        "w": 17.3,
        "h": 11.3,
    },
    {
        "id": "rg-commerce-edge",
        "type": "resource-group",
        "name": "rg-commerce-edge",
        "status": "healthy",
        "parent_id": "sub-commerce",
        "x": 0.9,
        "y": 1.25,
        "w": 5.2,
        "h": 9.4,
    },
    {
        "id": "rg-commerce-app",
        "type": "resource-group",
        "name": "rg-commerce-app",
        "status": "healthy",
        "parent_id": "sub-commerce",
        "x": 6.4,
        "y": 1.25,
        "w": 5.4,
        "h": 9.4,
    },
    {
        "id": "rg-commerce-data",
        "type": "resource-group",
        "name": "rg-commerce-data",
        "status": "healthy",
        "parent_id": "sub-commerce",
        "x": 12.1,
        "y": 1.25,
        "w": 5.0,
        "h": 9.4,
    },
    {
        "id": "vnet-commerce",
        "type": "virtual-network",
        "name": "vnet-commerce",
        "status": "healthy",
        "parent_id": "rg-commerce-edge",
        "x": 1.35,
        "y": 2.1,
        "w": 4.3,
        "h": 7.8,
    },
    {
        "id": "snet-commerce-ingress",
        "type": "subnet",
        "name": "snet-ingress",
        "status": "healthy",
        "parent_id": "vnet-commerce",
        "x": 1.7,
        "y": 2.8,
        "w": 3.6,
        "h": 2.4,
    },
    {
        "id": "commerce-frontdoor",
        "type": "front-door",
        "name": "commerce-frontdoor",
        "status": "healthy",
        "parent_id": "rg-commerce-edge",
        "x": 1.4,
        "y": 1.7,
    },
    {
        "id": "commerce-waf",
        "type": "application-gateway",
        "name": "commerce-waf",
        "status": "healthy",
        "parent_id": "snet-commerce-ingress",
        "x": 2.4,
        "y": 3.5,
    },
    {
        "id": "commerce-api",
        "type": "app-service",
        "name": "commerce-api",
        "status": "healthy",
        "parent_id": "rg-commerce-app",
        "x": 7.3,
        "y": 3.0,
    },
    {
        "id": "commerce-worker",
        "type": "container-app",
        "name": "order-worker",
        "status": "healthy",
        "parent_id": "rg-commerce-app",
        "x": 9.7,
        "y": 4.4,
    },
    {
        "id": "commerce-jobs",
        "type": "function-app",
        "name": "commerce-jobs",
        "status": "healthy",
        "parent_id": "rg-commerce-app",
        "x": 7.7,
        "y": 7.1,
    },
    {
        "id": "commerce-db",
        "type": "postgresql",
        "name": "orders-db",
        "status": "healthy",
        "parent_id": "rg-commerce-data",
        "x": 13.2,
        "y": 3.2,
    },
    {
        "id": "commerce-cache",
        "type": "redis",
        "name": "catalog-cache",
        "status": "warning",
        "parent_id": "rg-commerce-data",
        "x": 15.5,
        "y": 5.3,
    },
    {
        "id": "commerce-storage",
        "type": "storage-account",
        "name": "product-media",
        "status": "healthy",
        "parent_id": "rg-commerce-data",
        "x": 13.8,
        "y": 8.0,
    },
)

_OPERATIONS_RESOURCES: tuple[dict[str, Any], ...] = (
    {
        "id": "sub-operations",
        "type": "subscription",
        "name": "Operations subscription",
        "status": "healthy",
        "x": 0.35,
        "y": 0.35,
        "w": 17.3,
        "h": 11.3,
    },
    {
        "id": "rg-ops-network",
        "type": "resource-group",
        "name": "rg-ops-network",
        "status": "healthy",
        "parent_id": "sub-operations",
        "x": 0.9,
        "y": 1.25,
        "w": 5.0,
        "h": 9.4,
    },
    {
        "id": "rg-ops-app",
        "type": "resource-group",
        "name": "rg-ops-app",
        "status": "healthy",
        "parent_id": "sub-operations",
        "x": 6.2,
        "y": 1.25,
        "w": 5.3,
        "h": 9.4,
    },
    {
        "id": "rg-ops-data",
        "type": "resource-group",
        "name": "rg-ops-data",
        "status": "healthy",
        "parent_id": "sub-operations",
        "x": 11.8,
        "y": 1.25,
        "w": 5.3,
        "h": 9.4,
    },
    {
        "id": "vnet-ops",
        "type": "virtual-network",
        "name": "vnet-ops",
        "status": "healthy",
        "parent_id": "rg-ops-network",
        "x": 1.3,
        "y": 2.1,
        "w": 4.2,
        "h": 7.7,
    },
    {
        "id": "ops-waf",
        "type": "application-gateway",
        "name": "ops-waf",
        "status": "healthy",
        "parent_id": "rg-ops-network",
        "x": 2.3,
        "y": 3.3,
    },
    {
        "id": "ops-portal",
        "type": "app-service",
        "name": "operations-portal",
        "status": "healthy",
        "parent_id": "rg-ops-app",
        "x": 7.4,
        "y": 3.1,
    },
    {
        "id": "ops-api",
        "type": "container-app",
        "name": "operations-api",
        "status": "healthy",
        "parent_id": "rg-ops-app",
        "x": 9.8,
        "y": 4.7,
    },
    {
        "id": "ops-scheduler",
        "type": "function-app",
        "name": "ops-scheduler",
        "status": "warning",
        "parent_id": "rg-ops-app",
        "x": 7.8,
        "y": 7.4,
    },
    {
        "id": "ops-db",
        "type": "postgresql",
        "name": "operations-db",
        "status": "healthy",
        "parent_id": "rg-ops-data",
        "x": 13.0,
        "y": 3.2,
    },
    {
        "id": "ops-cache",
        "type": "redis",
        "name": "operations-cache",
        "status": "healthy",
        "parent_id": "rg-ops-data",
        "x": 15.2,
        "y": 5.6,
    },
    {
        "id": "ops-storage",
        "type": "storage-account",
        "name": "operations-archive",
        "status": "healthy",
        "parent_id": "rg-ops-data",
        "x": 13.7,
        "y": 8.1,
    },
)

_COMMERCE_LINKS: tuple[dict[str, str], ...] = (
    {"source": "sub-commerce", "target": "rg-commerce-edge", "type": "contains"},
    {"source": "sub-commerce", "target": "rg-commerce-app", "type": "contains"},
    {"source": "sub-commerce", "target": "rg-commerce-data", "type": "contains"},
    {"source": "rg-commerce-edge", "target": "vnet-commerce", "type": "contains"},
    {"source": "vnet-commerce", "target": "snet-commerce-ingress", "type": "contains"},
    {"source": "commerce-frontdoor", "target": "commerce-waf", "type": "depends_on"},
    {"source": "commerce-waf", "target": "commerce-api", "type": "depends_on"},
    {"source": "commerce-api", "target": "commerce-worker", "type": "depends_on"},
    {"source": "commerce-api", "target": "commerce-db", "type": "depends_on"},
    {"source": "commerce-api", "target": "commerce-cache", "type": "depends_on"},
    {"source": "commerce-worker", "target": "commerce-storage", "type": "attached_to"},
)

_OPERATIONS_LINKS: tuple[dict[str, str], ...] = (
    {"source": "sub-operations", "target": "rg-ops-network", "type": "contains"},
    {"source": "sub-operations", "target": "rg-ops-app", "type": "contains"},
    {"source": "sub-operations", "target": "rg-ops-data", "type": "contains"},
    {"source": "rg-ops-network", "target": "vnet-ops", "type": "contains"},
    {"source": "ops-waf", "target": "ops-portal", "type": "depends_on"},
    {"source": "ops-portal", "target": "ops-api", "type": "depends_on"},
    {"source": "ops-api", "target": "ops-db", "type": "depends_on"},
    {"source": "ops-api", "target": "ops-cache", "type": "depends_on"},
    {"source": "ops-scheduler", "target": "ops-storage", "type": "attached_to"},
)

_VIEWS: tuple[dict[str, str], ...] = (
    {
        "id": "fdai-control-plane",
        "label": "FDAI control plane",
        "kind": "fdai",
        "classification": "ownership_tag",
        "description": "FDAI's own runtime, state, network, and data dependencies",
        "root_resource_id": "sub-example",
    },
    {
        "id": "commerce-api",
        "label": "Commerce API",
        "kind": "service",
        "classification": "service_tag",
        "description": "Customer-facing commerce application managed by FDAI",
        "root_resource_id": "sub-commerce",
    },
    {
        "id": "operations-portal",
        "label": "Operations portal",
        "kind": "service",
        "classification": "service_tag",
        "description": "Internal operations application managed by FDAI",
        "root_resource_id": "sub-operations",
    },
)

_VIEW_GRAPHS = {
    "fdai-control-plane": (_FDAI_RESOURCES, _FDAI_LINKS),
    "commerce-api": (_COMMERCE_RESOURCES, _COMMERCE_LINKS),
    "operations-portal": (_OPERATIONS_RESOURCES, _OPERATIONS_LINKS),
}


async def demo_inventory_graph_provider(
    scope: str | None,
    depth: int,
    link_types: tuple[str, ...],
) -> dict[str, Any]:
    """Return a stable dev graph filtered by link type.

    Scope/depth are echoed in the route manifest. The small fixture remains
    complete so navigation and deep-link demos stay deterministic.
    """

    del depth
    if scope is not None and scope not in _VIEW_GRAPHS:
        raise InventoryGraphViewNotFoundError(f"architecture view not found: {scope}")
    active_view = scope or "fdai-control-plane"
    resources, links = _VIEW_GRAPHS[active_view]
    return {
        "snapshot_at": datetime.now(UTC).isoformat(),
        "freshness": "fresh",
        "source": "synthetic-dev",
        "active_view": active_view,
        "views": [dict(view) for view in _VIEWS],
        "resources": [dict(resource) for resource in resources],
        "links": [dict(link) for link in links if link["type"] in link_types],
        "truncated": False,
        "cursor": None,
    }


__all__ = ["demo_inventory_graph_provider"]
