"""Typed operational ontology platform primitives."""

from .action_plans import compile_action_mutation_plan, validate_action_plan_semantics
from .catalog_projection import (
    CatalogOntologyProjection,
    CatalogOntologyProjector,
    build_catalog_ontology_projection,
    merge_catalog_ontology_projections,
)
from .functions import (
    ContextualOntologyFunction,
    FunctionInvocationContext,
    FunctionInvocationReceipt,
    OntologyFunction,
    OntologyFunctionRegistry,
    ontology_function_digest,
)
from .interfaces import CompiledInterfaceCatalog, compile_interfaces
from .introspection import platform_manifest
from .kinetics import (
    ActionArgumentBinding,
    ActionReadSetReceipt,
    AuthorityClass,
    CriterionResult,
    MutationEffect,
    MutationEffectKind,
    MutationPlan,
    OntologyFunctionKind,
    OntologyFunctionType,
    ProjectionBinding,
    ReconciliationReceipt,
    ReconciliationStatus,
    TargetRevision,
)
from .metric_semantics import (
    CausalEvidenceJoin,
    CausalJoinStatus,
    MetricAggregation,
    MetricSemanticDefinition,
    MetricSemanticRegistry,
    MetricWindow,
    MetricWindowComparison,
    MetricWindowProvider,
    compare_aligned_windows,
    join_causal_evidence,
)
from .models import (
    InterfaceImplementation,
    ObjectPredicate,
    ObjectPredicateOperator,
    ObjectSelector,
    ObjectSelectorKind,
    ObjectSetDefinition,
    ObjectSetMaterialization,
    ObjectSetTruncationReason,
    ObjectTraversal,
    OntologyInterfaceType,
)
from .object_sets import ObjectSetService
from .planning import build_mutation_plan, validate_plan_revisions
from .projection import project_source_records, reconcile_expected_effects
from .query_execution import (
    ObjectSetNodeHandler,
    OntologyQueryPlanExecutor,
    QueryNodeHandler,
    QueryNodeResult,
    QueryPlanExecution,
)
from .query_handlers import (
    AggregateNodeHandler,
    OrderNodeHandler,
    ProjectNodeHandler,
    SetOperationNodeHandler,
)
from .query_manifest import QueryManifest, build_query_manifest
from .query_metric_handlers import (
    METRIC_ARGUMENT_SCHEMAS,
    EvidenceJoinNodeHandler,
    MetricSeriesNodeHandler,
)
from .query_source_handlers import FunctionNodeHandler, SecuredObjectSetNodeHandler
from .query_topology_handlers import (
    TOPOLOGY_ARGUMENT_SCHEMAS,
    TopologyAtNodeHandler,
    TopologyDiffNodeHandler,
)
from .query_values import QueryRow, QueryTable
from .query_verification import OntologyQueryPlanVerifier
from .sdk_codegen import GeneratedOntologySdk, generate_ontology_sdk
from .semantic_plans import (
    ActiveSemanticCatalog,
    InterpretationCandidateSource,
    SemanticBasisValidator,
    SemanticInterpretationCandidate,
    SemanticOperationClass,
    VerifiedInterpretationBasis,
    VerifiedSemanticPlan,
    build_semantic_candidate,
    verify_semantic_candidate,
)
from .topology_history import (
    TopologyDiff,
    TopologyGraphAt,
    TopologyHistoryReader,
    TopologyLinkRevision,
    TopologyObjectRevision,
    TopologyRevisionBatch,
    graph_at,
    topology_diff,
)

__all__ = [
    "ActionArgumentBinding",
    "ActionReadSetReceipt",
    "ActiveSemanticCatalog",
    "AggregateNodeHandler",
    "CatalogOntologyProjection",
    "CatalogOntologyProjector",
    "CompiledInterfaceCatalog",
    "AuthorityClass",
    "CriterionResult",
    "CausalEvidenceJoin",
    "CausalJoinStatus",
    "ContextualOntologyFunction",
    "GeneratedOntologySdk",
    "FunctionInvocationContext",
    "FunctionInvocationReceipt",
    "FunctionNodeHandler",
    "EvidenceJoinNodeHandler",
    "InterfaceImplementation",
    "InterpretationCandidateSource",
    "ObjectPredicate",
    "ObjectPredicateOperator",
    "ObjectSelector",
    "ObjectSelectorKind",
    "ObjectSetDefinition",
    "ObjectSetNodeHandler",
    "ObjectSetMaterialization",
    "ObjectSetTruncationReason",
    "ObjectSetService",
    "ObjectTraversal",
    "MutationEffect",
    "MutationEffectKind",
    "MutationPlan",
    "MetricAggregation",
    "METRIC_ARGUMENT_SCHEMAS",
    "MetricSemanticDefinition",
    "MetricSemanticRegistry",
    "MetricWindow",
    "MetricWindowComparison",
    "MetricWindowProvider",
    "MetricSeriesNodeHandler",
    "OntologyFunction",
    "OntologyFunctionKind",
    "OntologyFunctionRegistry",
    "ontology_function_digest",
    "OntologyFunctionType",
    "OntologyInterfaceType",
    "OntologyQueryPlanExecutor",
    "OntologyQueryPlanVerifier",
    "OrderNodeHandler",
    "ProjectionBinding",
    "ProjectNodeHandler",
    "QueryManifest",
    "QueryNodeHandler",
    "QueryNodeResult",
    "QueryPlanExecution",
    "QueryRow",
    "QueryTable",
    "ReconciliationReceipt",
    "ReconciliationStatus",
    "SemanticBasisValidator",
    "SemanticInterpretationCandidate",
    "SemanticOperationClass",
    "SecuredObjectSetNodeHandler",
    "SetOperationNodeHandler",
    "TargetRevision",
    "TopologyDiff",
    "TopologyDiffNodeHandler",
    "TopologyGraphAt",
    "TopologyHistoryReader",
    "TopologyAtNodeHandler",
    "TOPOLOGY_ARGUMENT_SCHEMAS",
    "TopologyLinkRevision",
    "TopologyObjectRevision",
    "TopologyRevisionBatch",
    "VerifiedInterpretationBasis",
    "VerifiedSemanticPlan",
    "build_mutation_plan",
    "build_query_manifest",
    "compile_action_mutation_plan",
    "build_semantic_candidate",
    "build_catalog_ontology_projection",
    "merge_catalog_ontology_projections",
    "compile_interfaces",
    "compare_aligned_windows",
    "generate_ontology_sdk",
    "graph_at",
    "join_causal_evidence",
    "platform_manifest",
    "project_source_records",
    "reconcile_expected_effects",
    "validate_plan_revisions",
    "validate_action_plan_semantics",
    "topology_diff",
    "verify_semantic_candidate",
]
