schema_version: 1.0.0
id: azure-builtin.object-storage.storage-account-should-restrict-ip-rules-in-storage-account-firewall-settings
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: object-storage
check_logic:
  kind: expression
  reference: azure-policy://d66025f8-6cad-476a-bbfb-3b66ae33f6ff
remediation:
  template_ref: remediation/azure-builtin/d66025f8-6cad-476a-bbfb-3b66ae33f6ff.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: d66025f8-6cad-476a-bbfb-3b66ae33f6ff
  azure_policy_display_name: Storage account should restrict IP rules in storage account
    firewall settings.
  azure_policy_effect_default: Audit
  azure_policy_category: Mission
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Mission/StorageAllowedIPRules_Audit.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
