schema_version: 1.0.0
id: azure-builtin.azure.web.sites.networkconfig.do-not-allow-delete-on-app-network-configuration
version: 1.0.0
source: azure_policy
severity: high
category: security
resource_type: azure.web.sites.networkconfig
check_logic:
  kind: expression
  reference: azure-policy://1d1e7723-ab70-4ce1-a12e-bf6977859d06
remediation:
  template_ref: remediation/azure-builtin/1d1e7723-ab70-4ce1-a12e-bf6977859d06.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 1d1e7723-ab70-4ce1-a12e-bf6977859d06
  azure_policy_display_name: Do not allow delete on App network configuration
  azure_policy_effect_default: DenyAction
  azure_policy_category: Mission
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Mission/AppDenyNetDelete_DenyAction.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
