schema_version: 1.0.0
id: azure-builtin.secret-store.configure-azure-key-vaults-with-private-endpoints
version: 1.0.1
source: azure_policy
severity: medium
category: security
resource_type: secret-store
check_logic:
  kind: expression
  reference: azure-policy://9d4fad1f-5189-4a42-b29e-cf7929c6b6df
remediation:
  template_ref: remediation/azure-builtin/9d4fad1f-5189-4a42-b29e-cf7929c6b6df.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 9d4fad1f-5189-4a42-b29e-cf7929c6b6df
  azure_policy_display_name: Configure Azure Key Vaults with private endpoints
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Key Vault
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Key Vault/Should_Use_PrivateEndpoint_DINE.json
  source_version: 1.0.1
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
