schema_version: 1.0.0
id: azure-builtin.compute.vm.windows-machines-should-be-configured-to-use-secure-communication-protocols
version: 3.1.0
source: azure_policy
severity: medium
category: compliance
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://5752e6d6-1206-46d8-8ab1-ecc2f71a8112
remediation:
  template_ref: remediation/azure-builtin/5752e6d6-1206-46d8-8ab1-ecc2f71a8112.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 5752e6d6-1206-46d8-8ab1-ecc2f71a8112
  azure_policy_display_name: Windows machines should be configured to use secure communication
    protocols
  azure_policy_effect_default: AuditIfNotExists
  azure_policy_category: Guest Configuration
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Guest Configuration/SecureWebProtocol_AINE.json
  source_version: 3.1.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
