schema_version: 1.0.0
id: azure-builtin.microsoft.web.sites.deprecated-deprecated-audit-web-applications-that-are-not-using-custom-domains
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: microsoft.web.sites
check_logic:
  kind: expression
  reference: azure-policy://dd2ea520-6b06-45c3-806e-ea297c23e06a
remediation:
  template_ref: remediation/azure-builtin/dd2ea520-6b06-45c3-806e-ea297c23e06a.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: dd2ea520-6b06-45c3-806e-ea297c23e06a
  azure_policy_display_name: '[Deprecated]: [Deprecated]: Audit Web Applications that
    are not using custom domains'
  azure_policy_effect_default: AuditIfNotExists
  azure_policy_category: Security Center
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Security Center/ASC_UsedCustomDomains_WebApp_Audit_Deprecated.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
