schema_version: 1.0.0
id: azure-builtin.azure.sqlvirtualmachine.sqlvirtualmachines.configure-the-microsoft-defender-for-sql-log-analytics-workspace
version: 1.5.0
source: azure_policy
severity: medium
category: security
resource_type: azure.sqlvirtualmachine.sqlvirtualmachines
check_logic:
  kind: expression
  reference: azure-policy://242300d6-1bfc-4d64-8d01-cee583709ebd
remediation:
  template_ref: remediation/azure-builtin/242300d6-1bfc-4d64-8d01-cee583709ebd.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 242300d6-1bfc-4d64-8d01-cee583709ebd
  azure_policy_display_name: Configure the Microsoft Defender for SQL Log Analytics
    workspace
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Security Center
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Security Center/MDC_DfSQL_DeployDefaultWorkspace.json
  source_version: 1.5.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
