schema_version: 1.0.0
id: azure-builtin.compute.vm.deploy-the-linux-guest-configuration-extension-to-enable-guest-configuration-assignments-on-linux-vm
version: 1.4.0
source: azure_policy
severity: medium
category: compliance
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://331e8ea8-378a-410f-a2e5-ae22f38bb0da
remediation:
  template_ref: remediation/azure-builtin/331e8ea8-378a-410f-a2e5-ae22f38bb0da.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 331e8ea8-378a-410f-a2e5-ae22f38bb0da
  azure_policy_display_name: Deploy the Linux Guest Configuration extension to enable
    Guest Configuration assignments on Linux VMs
  azure_policy_effect_default: deployIfNotExists
  azure_policy_category: Guest Configuration
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Guest Configuration/DeployExtensionLinux_Prerequisite.json
  source_version: 1.4.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
