schema_version: 1.0.0
id: azure-builtin.compute.vm.configure-windows-virtual-machines-to-run-azure-monitor-agent-using-system-assigned-managed-identity
version: 4.6.0
source: azure_policy
severity: medium
category: compliance
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://ca817e41-e85a-4783-bc7f-dc532d36235e
remediation:
  template_ref: remediation/azure-builtin/ca817e41-e85a-4783-bc7f-dc532d36235e.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: ca817e41-e85a-4783-bc7f-dc532d36235e
  azure_policy_display_name: Configure Windows virtual machines to run Azure Monitor
    Agent using system-assigned managed identity
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Monitoring
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Monitoring/AzureMonitor_Agent_Windows_VM_DINE.json
  source_version: 4.6.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
