schema_version: 1.0.0
id: azure-builtin.azure.guestconfiguration.guestconfigurationassignments.private-endpoints-for-guest-configuration-assignments-shoul
version: 1.0.0
source: azure_policy
severity: medium
category: compliance
resource_type: azure.guestconfiguration.guestconfigurationassignments
check_logic:
  kind: expression
  reference: azure-policy://480d0f91-30af-4a76-9afb-f5710ac52b09
remediation:
  template_ref: remediation/azure-builtin/480d0f91-30af-4a76-9afb-f5710ac52b09.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 480d0f91-30af-4a76-9afb-f5710ac52b09
  azure_policy_display_name: Private endpoints for Guest Configuration assignments
    should be enabled
  azure_policy_effect_default: Audit
  azure_policy_category: Guest Configuration
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Government/Guest Configuration/Azure_PrivateLink_Deny.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
