schema_version: 1.0.0
id: azure-builtin.kubernetes-cluster.preview-deploy-image-integrity-on-azure-kubernetes-service
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: kubernetes-cluster
check_logic:
  kind: expression
  reference: azure-policy://5dc99dae-cfb2-42cc-8762-9aae02b74e27
remediation:
  template_ref: remediation/azure-builtin/5dc99dae-cfb2-42cc-8762-9aae02b74e27.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 5dc99dae-cfb2-42cc-8762-9aae02b74e27
  azure_policy_display_name: '[Preview]: Deploy Image Integrity on Azure Kubernetes
    Service'
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Kubernetes
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Kubernetes/AKS_ImageIntegrity_DINE.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
