"""Ontology types and event / action / rule schemas (versioned).

Ontology (Resource / Rule / Signal / Finding) plus event / action / rule
schemas. Public API. Re-exports the *interfaces* (Protocols, data models,
errors) that core modules depend on. Concrete implementations
(``PackageResourceSchemaRegistry``, ``JsonSchemaContractValidator``,
``JsonSchemaEventValidator``) are **intentionally not re-exported here** - they
must be imported from their submodules by the composition root only, so
``core/`` cannot accidentally depend on a concrete adapter (see
``docs/roadmap/architecture/project-structure.md § Customization via Dependency Injection``).
"""

from .models import (
    AccessDescriptor,
    Action,
    ActionBlastRadius,
    ActionInterface,
    ActionPrecondition,
    ActionStopCondition,
    BestPractice,
    BestPracticeRequirement,
    BlastRadius,
    BlastRadiusComputation,
    BlastRadiusScope,
    Category,
    CausalEvidenceGrade,
    CheckLogic,
    CheckLogicKind,
    Decision,
    DocumentEnvelope,
    DocumentPurpose,
    DocumentSourceSpan,
    DocumentState,
    DocumentVersion,
    DocumentWorkerAuditEvent,
    DocumentWorkerClaim,
    DocumentWorkerClaimStatus,
    DocumentWorkerIndexCommand,
    DocumentWorkerStage,
    Event,
    ExecutorCommand,
    ExecutorEffectReceipt,
    ExecutorEffectReceiptStatus,
    ExecutorShadowReceipt,
    ExecutorShadowReceiptStatus,
    ForecastMissOrigin,
    ForecastOutcome,
    ForecastOutcomeLabel,
    IdempotencyKey,
    IngestionCapabilities,
    KnowledgeEvidenceEvent,
    KnowledgeEvidenceEventType,
    LifecycleCriterion,
    LifecycleDeduplication,
    LifecycleOwner,
    LinkCardinality,
    LogicCapability,
    LogicExecutionClass,
    MalwareVerdict,
    Mode,
    ObjectLifecycle,
    OntologyActionType,
    OntologyFunctionKind,
    OntologyFunctionType,
    OntologyLinkType,
    OntologyObjectType,
    OntologyProvenance,
    Operation,
    PreconditionKind,
    PromotionGate,
    PropertyDecl,
    PropertyType,
    ProtectionState,
    Provenance,
    Remediation,
    RequirementKind,
    RequirementMode,
    RequirementOutcome,
    RequirementStatus,
    ResponseOutcome,
    ResponseOutcomeLabel,
    ResponseVerificationStatus,
    RetentionPolicy,
    RollbackKind,
    RollbackRef,
    Rule,
    RuleInterface,
    RuleSource,
    SemVer,
    Severity,
    SourceStorageMode,
    StopConditionKind,
    StructuralUnit,
    SubmissionCriterion,
    SubmissionCriterionKind,
    TelemetryCompleteness,
    Tier,
    UploadSession,
)
from .models.executor_transport import executor_action_payload_digest
from .registry import SchemaNotFoundError, SchemaRegistry
from .validation import (
    ContractValidationError,
    ContractValidator,
    EventValidator,
    ValidationIssue,
)

__all__ = [
    # data - enums
    "ActionInterface",
    "BlastRadiusComputation",
    "BlastRadiusScope",
    "BestPractice",
    "BestPracticeRequirement",
    "Category",
    "CausalEvidenceGrade",
    "CheckLogicKind",
    "Decision",
    "LinkCardinality",
    "Mode",
    "Operation",
    "PreconditionKind",
    "PropertyType",
    "RollbackKind",
    "RuleSource",
    "Severity",
    "StopConditionKind",
    "TelemetryCompleteness",
    "Tier",
    # data - aliases
    "IdempotencyKey",
    "SemVer",
    # data - models
    "Action",
    "ActionBlastRadius",
    "ActionPrecondition",
    "ActionStopCondition",
    "BlastRadius",
    "CheckLogic",
    "Event",
    "ExecutorCommand",
    "ExecutorEffectReceipt",
    "ExecutorEffectReceiptStatus",
    "ExecutorShadowReceipt",
    "ExecutorShadowReceiptStatus",
    "executor_action_payload_digest",
    "ForecastOutcome",
    "ForecastOutcomeLabel",
    "ForecastMissOrigin",
    "LifecycleCriterion",
    "LifecycleDeduplication",
    "LifecycleOwner",
    "LogicCapability",
    "LogicExecutionClass",
    "ObjectLifecycle",
    "OntologyActionType",
    "OntologyFunctionKind",
    "OntologyFunctionType",
    "OntologyLinkType",
    "OntologyObjectType",
    "OntologyProvenance",
    "PromotionGate",
    "PropertyDecl",
    "Provenance",
    "Remediation",
    "RequirementKind",
    "RequirementMode",
    "RequirementOutcome",
    "RequirementStatus",
    "ResponseOutcome",
    "ResponseOutcomeLabel",
    "ResponseVerificationStatus",
    "RollbackRef",
    "Rule",
    "RuleInterface",
    "SubmissionCriterion",
    "SubmissionCriterionKind",
    # DI seams (Protocols only - no concretes)
    "ContractValidator",
    "EventValidator",
    "SchemaRegistry",
    "AccessDescriptor",
    "DocumentEnvelope",
    "DocumentSourceSpan",
    "DocumentPurpose",
    "DocumentState",
    "DocumentVersion",
    "DocumentWorkerClaim",
    "DocumentWorkerClaimStatus",
    "DocumentWorkerAuditEvent",
    "DocumentWorkerIndexCommand",
    "DocumentWorkerStage",
    "IngestionCapabilities",
    "KnowledgeEvidenceEvent",
    "KnowledgeEvidenceEventType",
    "MalwareVerdict",
    "ProtectionState",
    "RetentionPolicy",
    "SourceStorageMode",
    "StructuralUnit",
    "UploadSession",
    # error types
    "ContractValidationError",
    "SchemaNotFoundError",
    "ValidationIssue",
]
