from __future__ import annotations

import json
import os
import runpy
import shutil
import subprocess
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
LAB_SCRIPTS = REPO_ROOT / "scripts" / "deployment" / "scenario-lab"
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "sre-demo-lab.yml"
ADOPTION = runpy.run_path(str(LAB_SCRIPTS / "adopt_retained_resources.py"))
SCOPE_CASE_FILTER = LAB_SCRIPTS / "scope-case-replacements.jq"
JQ = shutil.which("jq")
BASH = shutil.which("bash")

SUB = "00000000-0000-0000-0000-000000000001"
RG = "rg-lab-example"
RUNNER = "00000000-0000-0000-0000-0000000000aa"
GROUP_ID = f"/subscriptions/{SUB}/resourceGroups/{RG}"
AKS_ID = f"{GROUP_ID}/providers/Microsoft.ContainerService/managedClusters/aks-store-demo"
MYSQL_ID = f"{GROUP_ID}/providers/Microsoft.DBforMySQL/flexibleServers/mysql-fdai-sre-0a1b2c"
NIC_ID = f"{GROUP_ID}/providers/Microsoft.Network/networkInterfaces/nic-fdai-sre-lab-krc-stress"
NSG_ID = f"{GROUP_ID}/providers/Microsoft.Network/networkSecurityGroups/nsg-fdai-sre-lab-krc"
OWNED = {
    "fdai:managed": "true",
    "fdai:layer": "scenario-lab",
    "fdai:env": "lab",
    "fdai:workload": "fdai",
    "fdai:managed-by": "azure-cli-recovery",
}
USER_ROLE = "Azure Kubernetes Service Cluster User Role"
ADMIN_ROLE = "Azure Kubernetes Service RBAC Cluster Admin"


def _scope() -> Any:
    return ADOPTION["Scope"](SUB, RG, "krc", RUNNER)


def _row(resource_type: str, name: str, resource_id: str, tags: dict[str, str] = OWNED) -> dict:
    return {"type": resource_type, "name": name, "id": resource_id.lower(), "tags": dict(tags)}


def _assignment(role: str, guid: str, **overrides: object) -> dict:
    lowered_scope = AKS_ID.replace("/resourceGroups/", "/resourcegroups/")
    assignment = {
        "id": f"{lowered_scope}/providers/Microsoft.Authorization/roleAssignments/{guid}",
        "principalId": RUNNER,
        "roleDefinitionName": role,
        "scope": lowered_scope,
        "condition": None,
    }
    assignment.update(overrides)
    return assignment


def _resources(*, aks_tags: dict[str, str] = OWNED) -> list[dict]:
    return [
        _row("Microsoft.ContainerService/managedClusters", "aks-store-demo", AKS_ID, aks_tags),
        _row("Microsoft.DBforMySQL/flexibleServers", "mysql-fdai-sre-0a1b2c", MYSQL_ID),
        _row("Microsoft.Network/networkInterfaces", "nic-fdai-sre-lab-krc-stress", NIC_ID),
    ]


class FakeAz:
    def __init__(self, resources: list[dict], assignments: list[dict], nsg_id: str | None):
        self.resources = resources
        self.assignments = assignments
        self.nsg_id = nsg_id
        self.calls: list[tuple[str, ...]] = []

    def __call__(self, arguments: Sequence[str]) -> Any:
        self.calls.append(tuple(arguments[:3]))
        if arguments[:2] == ["resource", "list"]:
            return self.resources
        if arguments[:3] == ["role", "assignment", "list"]:
            return self.assignments
        if arguments[:3] == ["network", "nic", "show"]:
            return {"networkSecurityGroup": {"id": self.nsg_id} if self.nsg_id else None}
        raise AssertionError(arguments)


def _observed(**kwargs: Any) -> Any:
    fake = FakeAz(
        kwargs.get("resources", _resources()),
        kwargs.get(
            "assignments",
            [
                _assignment(USER_ROLE, "00000000-0000-0000-0000-000000000011"),
                _assignment(ADMIN_ROLE, "00000000-0000-0000-0000-000000000022"),
            ],
        ),
        kwargs.get("nsg_id", NSG_ID.lower()),
    )
    return ADOPTION["observe"](fake, _scope(), kwargs.get("state", frozenset()))


def test_retained_lab_resources_become_exact_canonical_imports() -> None:
    blocks = ADOPTION["plan_imports"](_scope(), frozenset(), "0a1b2c", _observed())

    assert [(block.address, block.resource_id) for block in blocks] == [
        ("azurerm_kubernetes_cluster.scenario_lab", AKS_ID),
        ("azurerm_mysql_flexible_server.scenario_lab", MYSQL_ID),
        (
            "azurerm_role_assignment.runner_aks_credentials",
            f"{AKS_ID}/providers/Microsoft.Authorization/roleAssignments/"
            "00000000-0000-0000-0000-000000000011",
        ),
        (
            "azurerm_role_assignment.runner_aks_admin",
            f"{AKS_ID}/providers/Microsoft.Authorization/roleAssignments/"
            "00000000-0000-0000-0000-000000000022",
        ),
        (
            "azurerm_network_interface_security_group_association.stress_vm",
            f"{NIC_ID}|{NSG_ID}",
        ),
    ]
    rendered = ADOPTION["render_imports"](blocks)
    assert rendered.startswith("# Generated by adopt_retained_resources.py")
    assert rendered.count("import {") == 5
    assert f'  id = "{AKS_ID}"' in rendered


def test_recorded_or_absent_resources_are_not_imported() -> None:
    state = frozenset(
        {
            "azurerm_kubernetes_cluster.scenario_lab",
            "azurerm_role_assignment.runner_aks_credentials",
            "azurerm_role_assignment.runner_aks_admin",
        }
    )
    observed = _observed(state=state, nsg_id=None)

    blocks = ADOPTION["plan_imports"](_scope(), state, None, observed)

    assert blocks == []
    empty = _observed(resources=[], assignments=[])
    assert ADOPTION["plan_imports"](_scope(), frozenset(), "0a1b2c", empty) == []


@pytest.mark.parametrize(
    ("kwargs", "message"),
    [
        ({"resources": _resources(aks_tags={**OWNED, "fdai:layer": "platform"})}, "fdai:layer"),
        ({"resources": _resources(aks_tags={})}, "fdai:managed"),
        (
            {
                "assignments": [
                    _assignment(USER_ROLE, "00000000-0000-0000-0000-000000000011"),
                    _assignment(USER_ROLE, "00000000-0000-0000-0000-000000000033"),
                ]
            },
            "more than one",
        ),
        (
            {
                "assignments": [
                    _assignment(
                        USER_ROLE,
                        "00000000-0000-0000-0000-000000000011",
                        condition="@Resource[x] == 'y'",
                    )
                ]
            },
            "conditional",
        ),
        ({"nsg_id": NSG_ID.replace("nsg-fdai-sre-lab-krc", "nsg-policy")}, "outside"),
    ],
)
def test_adoption_refuses_resources_that_are_not_the_exact_lab_resource(
    kwargs: dict[str, Any], message: str
) -> None:
    with pytest.raises(ADOPTION["AdoptionRefusedError"], match=message):
        ADOPTION["plan_imports"](_scope(), frozenset(), "0a1b2c", _observed(**kwargs))


def test_adoption_refuses_a_same_named_resource_in_another_group() -> None:
    moved = _resources()
    moved[0]["id"] = AKS_ID.replace(RG, "rg-other").lower()

    with pytest.raises(ADOPTION["AdoptionRefusedError"], match="exact scenario-lab resource id"):
        ADOPTION["plan_imports"](_scope(), frozenset(), None, _observed(resources=moved))


def test_observe_reads_only_what_missing_state_requires() -> None:
    fake = FakeAz(_resources(), [], None)
    state = frozenset(
        {
            "azurerm_role_assignment.runner_aks_credentials",
            "azurerm_role_assignment.runner_aks_admin",
            "azurerm_network_interface_security_group_association.stress_vm",
        }
    )

    ADOPTION["observe"](fake, _scope(), state)

    assert fake.calls == [("resource", "list", "--resource-group")]


def test_adoption_cli_writes_imports_and_outputs(tmp_path: Path, capsys) -> None:
    state_file = tmp_path / "state.txt"
    state_file.write_text("azurerm_private_dns_zone.mysql\n", encoding="utf-8")
    output = tmp_path / "retained-adoption.generated.tf"
    github_output = tmp_path / "github-output"
    fake = FakeAz(_resources(), [], None)
    arguments = [
        "--state-addresses",
        str(state_file),
        "--output",
        str(output),
        "--mysql-zone-name",
        "0a1b2c.mysql.database.azure.com",
        "--github-output",
        str(github_output),
        "--subscription-id",
        SUB.upper(),
        "--resource-group",
        RG,
        "--region-short",
        "krc",
        "--runner-principal-id",
        RUNNER,
    ]

    assert ADOPTION["main"](arguments, fake) == 0

    stdout = capsys.readouterr().out
    assert "adopt\tazurerm_kubernetes_cluster.scenario_lab" in stdout
    assert "adopt\tazurerm_mysql_flexible_server.scenario_lab" in stdout
    assert "Scenario lab retained-resource adoption: 2 import." in stdout
    assert SUB not in stdout
    assert output.read_text(encoding="utf-8").count("import {") == 2
    assert github_output.read_text(encoding="utf-8").splitlines() == [
        "import_count=2",
        "mysql_server_name=mysql-fdai-sre-0a1b2c",
    ]

    refused = FakeAz(_resources(aks_tags={**OWNED, "fdai:managed": "false"}), [], None)
    assert ADOPTION["main"](arguments, refused) == 1
    assert "adoption refused" in capsys.readouterr().err

    assert ADOPTION["main"](arguments, FakeAz([], [], None)) == 0
    assert not output.exists()
    bad_scope = [*arguments[:-1], "not-a-guid"]
    assert ADOPTION["main"](bad_scope, fake) == 2


def _plan_change(address: str, before_scope: str, after_scope: str, **overrides: Any) -> dict:
    change = {
        "actions": ["delete", "create"],
        "replace_paths": [["scope"]],
        "importing": {"id": "retained"},
        "before": {
            "scope": before_scope,
            "principal_id": RUNNER,
            "role_definition_name": USER_ROLE,
        },
        "after": {"scope": after_scope, "principal_id": RUNNER, "role_definition_name": USER_ROLE},
    }
    change.update(overrides)
    return {"address": address, "change": change}


@pytest.mark.skipif(JQ is None, reason="jq is required by the protected workflow")
def test_apply_accepts_only_case_normalizing_runner_grant_replacements(tmp_path: Path) -> None:
    lowered = AKS_ID.replace("/resourceGroups/", "/resourcegroups/")
    other_cluster = AKS_ID.replace("aks-store-demo", "aks-other")
    plan = {
        "resource_changes": [
            _plan_change("azurerm_role_assignment.runner_aks_credentials", lowered, AKS_ID),
            _plan_change("azurerm_role_assignment.runner_aks_admin", AKS_ID, other_cluster),
            _plan_change("azurerm_role_assignment.aks_network_contributor", lowered, AKS_ID),
            _plan_change(
                "azurerm_role_assignment.runner_aks_admin",
                lowered,
                AKS_ID,
                replace_paths=[["scope"], ["principal_id"]],
            ),
            _plan_change(
                "azurerm_role_assignment.runner_aks_admin",
                lowered,
                AKS_ID,
                actions=["create"],
            ),
        ]
    }
    plan_file = tmp_path / "plan.json"
    plan_file.write_text(json.dumps(plan), encoding="utf-8")

    result = subprocess.run(  # noqa: S603 - resolved jq and repository filter.
        [str(JQ), "-c", "-f", str(SCOPE_CASE_FILTER), str(plan_file)],
        capture_output=True,
        check=True,
        text=True,
    )

    assert json.loads(result.stdout) == ["azurerm_role_assignment.runner_aks_credentials"]


def _step(workflow: str, name: str) -> str:
    start = workflow.index(f"      - name: {name}\n")
    end = workflow.find("\n      - name: ", start + 1)
    return workflow[start : end if end != -1 else len(workflow)]


def test_workflow_adopts_starts_and_restores_the_retained_lab_in_order() -> None:
    workflow = WORKFLOW.read_text(encoding="utf-8")
    adoption = _step(workflow, "Adopt retained scenario-lab compute and data")
    start = _step(workflow, "Start retained scenario-lab compute and data")
    plan = _step(workflow, "Build bounded plan")
    restore = _step(workflow, "Restore AKS power state")
    order = [
        "Adopt succeeded partial-apply network resources",
        "Adopt retained scenario-lab compute and data",
        "Start retained scenario-lab compute and data",
        "Build bounded plan",
        "Apply exact plan",
        "Verify running AKS target",
        "Configure AKS test substrate",
        "Retain AKS Store Demo readback",
        "Upload AKS Store Demo readback evidence",
        "Run approved reference sweep",
        "Restore AKS power state",
        "Clean runner artifacts",
        "Revoke bounded scenario-lab deployment authority",
    ]

    positions = [workflow.index(f"      - name: {name}\n") for name in order]
    assert positions == sorted(positions)
    assert "inputs.action == 'plan' ||" in adoption
    assert "destroy" not in adoption.split("run: |", 1)[0]
    assert "--output retained-adoption.generated.tf" in adoption
    assert "terraform import" not in adoption
    assert "if: inputs.action == 'apply' || inputs.action == 'recreate-aks'" in start
    assert ': >"$RUNNER_TEMP/sre-demo-lab-aks-started-by-run"' in start
    assert "timeout 900 az mysql flexible-server start" in start
    assert "flexible-server stop" not in workflow
    assert "scope-case-replacements.jq" in plan
    assert '"$((delete_count - scope_case_count))" -ne 0' in plan
    assert "import\\t\\(.address)" in plan
    assert "run_reference_sweep" not in restore
    assert "(inputs.action == 'apply' || inputs.action == 'recreate-aks')" in restore
    assert "terraform output" not in restore
    assert '"infra/scenario-lab/retained-adoption.generated.tf"' in workflow
    assert "infra/scenario-lab/retained-adoption.generated.tf" in (
        REPO_ROOT / ".gitignore"
    ).read_text(encoding="utf-8")


def test_prepare_waits_for_replaced_cluster_grants_before_kubernetes_calls() -> None:
    prepare = (LAB_SCRIPTS / "prepare-runner.sh").read_text(encoding="utf-8")
    wait = prepare.index("kubectl auth can-i create namespaces --quiet")

    assert prepare.index('kubelogin convert-kubeconfig --kubeconfig "$kubeconfig" -l msi') < wait
    assert wait < prepare.index("helm repo add chaos-mesh")
    assert "readonly kubernetes_authorization_deadline_seconds=300" in prepare
    assert "Kubernetes authorization did not propagate within five minutes." in prepare
    rollout = prepare.index('rollout status "$deployment" --timeout=15m')
    assert prepare.index("wait --for=condition=available deployment") < rollout
    assert rollout < prepare.index("verify_store_front_domain.py")


FAKE_AZ = """#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"$FAKE_AZ_LOG"
if [[ "$*" == *"aks stop"* ]]; then
  printf 'Stopped' >"$FAKE_AZ_POWER"
  exit 0
fi
if [[ "$*" == *"[[provisioningState, powerState.code]]"* ]]; then
  row="$(head -n 1 "$FAKE_AZ_ROWS")"
  tail -n +2 "$FAKE_AZ_ROWS" >"$FAKE_AZ_ROWS.next" && mv "$FAKE_AZ_ROWS.next" "$FAKE_AZ_ROWS"
  [[ "$row" == "fail" ]] && exit 1
  printf '%b\n' "$row"
  exit 0
fi
if [[ "$*" == *"--query powerState.code"* ]]; then
  cat "$FAKE_AZ_POWER"
  exit 0
fi
exit 2
"""


def _run_restore(tmp_path: Path, rows: list[str]) -> tuple[int, list[str]]:
    workflow = WORKFLOW.read_text(encoding="utf-8")
    step = _step(workflow, "Restore AKS power state")
    script = "\n".join(
        line.removeprefix("          ") for line in step.split("run: |\n", 1)[1].splitlines()
    )
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    (bin_dir / "az").write_text(FAKE_AZ, encoding="utf-8")
    (bin_dir / "sleep").write_text("#!/usr/bin/env bash\nexit 0\n", encoding="utf-8")
    for tool in ("az", "sleep"):
        (bin_dir / tool).chmod(0o755)
    (tmp_path / "rows").write_text("\n".join(rows) + "\n", encoding="utf-8")
    (tmp_path / "power").write_text("Running", encoding="utf-8")
    (tmp_path / "sre-demo-lab-aks-started-by-run").write_text("", encoding="utf-8")
    environment = {
        "PATH": f"{bin_dir}:{os.environ.get('PATH', '')}",
        "RUNNER_TEMP": str(tmp_path),
        "SCENARIO_LAB_RESOURCE_GROUP_NAME": RG,
        "FAKE_AZ_LOG": str(tmp_path / "az.log"),
        "FAKE_AZ_ROWS": str(tmp_path / "rows"),
        "FAKE_AZ_POWER": str(tmp_path / "power"),
    }
    result = subprocess.run(  # noqa: S603 - resolved Bash and an extracted repository step.
        [str(BASH), "-c", script],
        capture_output=True,
        check=False,
        env=environment,
        text=True,
        timeout=60,
    )
    log = (tmp_path / "az.log").read_text(encoding="utf-8").splitlines()
    return result.returncode, log


@pytest.mark.parametrize(
    ("rows", "stops"),
    [
        (["Succeeded\\tStopped"], 0),
        (["Updating\\tRunning", "Succeeded\\tRunning"], 1),
        (["fail", "Succeeded\\tRunning"], 1),
        (["Failed\\tRunning"], 1),
    ],
)
def test_restore_settles_a_running_operation_before_one_bounded_stop(
    tmp_path: Path, rows: list[str], stops: int
) -> None:
    returncode, log = _run_restore(tmp_path, rows)

    assert returncode == 0
    assert sum("aks stop" in line for line in log) == stops


FAKE_START_AZ = """#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"$FAKE_AZ_LOG"
next_result() {
  local results="$1"
  local result
  result="$(head -n 1 "$results")"
  tail -n +2 "$results" >"$results.next" && mv "$results.next" "$results"
  case "$result" in
    auth)
      printf "ERROR: (AuthorizationFailed) The client 'leak-client' with object id "
      printf "'leak-object' does not have authorization over scope '/subscriptions/leak'.\n"
      printf 'Code: AuthorizationFailed\n'
      exit 1
      ;;
    other)
      printf "ERROR: (OperationNotAllowed) leak-message for '/subscriptions/leak'.\n"
      printf 'Code: OperationNotAllowed\n'
      exit 1
      ;;
  esac
}
if [[ "$*" == "resource list"* ]]; then
  printf '1\n'
  exit 0
fi
if [[ "$*" == "aks start"* ]]; then
  next_result "$FAKE_AZ_AKS_RESULTS"
  printf 'Running' >"$FAKE_AZ_POWER"
  exit 0
fi
if [[ "$*" == "aks show"* ]]; then
  cat "$FAKE_AZ_POWER"
  printf '\n'
  exit 0
fi
if [[ "$*" == "mysql flexible-server start"* ]]; then
  next_result "$FAKE_AZ_MYSQL_RESULTS"
  printf 'Ready' >"$FAKE_AZ_MYSQL"
  exit 0
fi
if [[ "$*" == "mysql flexible-server show"* ]]; then
  cat "$FAKE_AZ_MYSQL"
  printf '\n'
  exit 0
fi
exit 2
"""


def _run_start(
    tmp_path: Path, aks_results: list[str], mysql_results: list[str]
) -> tuple[subprocess.CompletedProcess[str], list[str]]:
    workflow = WORKFLOW.read_text(encoding="utf-8")
    step = _step(workflow, "Start retained scenario-lab compute and data")
    script = "\n".join(
        line.removeprefix("          ") for line in step.split("run: |\n", 1)[1].splitlines()
    )
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    (bin_dir / "az").write_text(FAKE_START_AZ, encoding="utf-8")
    (bin_dir / "sleep").write_text("#!/usr/bin/env bash\nexit 0\n", encoding="utf-8")
    for tool in ("az", "sleep"):
        (bin_dir / tool).chmod(0o755)
    (tmp_path / "aks-results").write_text("\n".join([*aks_results, "ok"]) + "\n", encoding="utf-8")
    (tmp_path / "mysql-results").write_text(
        "\n".join([*mysql_results, "ok"]) + "\n", encoding="utf-8"
    )
    (tmp_path / "power").write_text("Stopped", encoding="utf-8")
    (tmp_path / "mysql").write_text("Stopped", encoding="utf-8")
    environment = {
        "PATH": f"{bin_dir}:{os.environ.get('PATH', '')}",
        "RUNNER_TEMP": str(tmp_path),
        "GITHUB_STEP_SUMMARY": str(tmp_path / "summary.md"),
        "SCENARIO_LAB_RESOURCE_GROUP_NAME": RG,
        "MYSQL_SERVER_NAME": "mysql-fdai-sre-0a1b2c",
        "FAKE_AZ_LOG": str(tmp_path / "az.log"),
        "FAKE_AZ_AKS_RESULTS": str(tmp_path / "aks-results"),
        "FAKE_AZ_MYSQL_RESULTS": str(tmp_path / "mysql-results"),
        "FAKE_AZ_POWER": str(tmp_path / "power"),
        "FAKE_AZ_MYSQL": str(tmp_path / "mysql"),
    }
    result = subprocess.run(  # noqa: S603 - resolved Bash and an extracted repository step.
        [str(BASH), "-c", script],
        capture_output=True,
        check=False,
        env=environment,
        text=True,
        timeout=60,
    )
    log = (tmp_path / "az.log").read_text(encoding="utf-8").splitlines()
    return result, log


def test_start_retries_only_propagating_authorization_for_each_target(tmp_path: Path) -> None:
    result, log = _run_start(tmp_path, ["auth", "auth"], ["auth"])
    output = result.stdout + result.stderr

    assert result.returncode == 0, result.stderr
    assert sum(line.startswith("aks start") for line in log) == 3
    assert sum(line.startswith("mysql flexible-server start") for line in log) == 2
    assert "Waiting for scenario-lab AKS start authorization (2/20)." in result.stdout
    assert "Waiting for scenario-lab MySQL start authorization (1/20)." in result.stdout
    assert (tmp_path / "sre-demo-lab-aks-started-by-run").is_file()
    assert "leak" not in output
    assert "/subscriptions/" not in output


def test_start_reports_only_the_code_of_a_non_authorization_failure(tmp_path: Path) -> None:
    result, log = _run_start(tmp_path, ["other"], [])

    assert result.returncode == 1
    assert sum(line.startswith("aks start") for line in log) == 1
    assert not any(line.startswith("mysql flexible-server start") for line in log)
    assert result.stderr == "scenario-lab AKS start failed (OperationNotAllowed).\n"
    assert (tmp_path / "sre-demo-lab-aks-started-by-run").is_file()


def test_start_stops_retrying_authorization_after_a_bounded_window(tmp_path: Path) -> None:
    result, log = _run_start(tmp_path, ["auth"] * 25, [])

    assert result.returncode == 1
    assert sum(line.startswith("aks start") for line in log) == 20
    assert result.stderr == (
        "scenario-lab AKS start authorization did not propagate within five minutes.\n"
    )
    assert "leak" not in result.stdout + result.stderr


STATE_INSTANCES_FILTER = LAB_SCRIPTS / "state-instances.jq"


@pytest.mark.skipif(JQ is None, reason="jq is required by the protected workflow")
def test_raw_state_reads_survive_attributes_the_provider_schema_dropped(tmp_path: Path) -> None:
    state = {
        "version": 4,
        "resources": [
            {
                "mode": "managed",
                "type": "azurerm_private_dns_zone",
                "name": "mysql",
                "instances": [{"attributes": {"name": "0a1b2c.mysql.database.azure.com"}}],
            },
            {
                "mode": "managed",
                "type": "azurerm_private_dns_zone_virtual_network_link",
                "name": "mysql_operator",
                "instances": [{"index_key": 0, "attributes": {"id": "link-id", "store": 1}}],
            },
            {
                "module": "module.azure_openai_private_endpoint",
                "mode": "managed",
                "type": "azurerm_private_dns_zone_virtual_network_link",
                "name": "extra",
                "instances": [{"index_key": "runner", "attributes": {"id": "extra-id"}}],
            },
            {
                "mode": "data",
                "type": "azurerm_resource_group",
                "name": "scenario_lab",
                "instances": [{"attributes": {"name": "ignored"}}],
            },
        ],
    }
    state_file = tmp_path / "state.json"
    state_file.write_text(json.dumps(state), encoding="utf-8")

    result = subprocess.run(  # noqa: S603 - resolved jq and repository filter.
        [str(JQ), "-c", "-f", str(STATE_INSTANCES_FILTER), str(state_file)],
        capture_output=True,
        check=True,
        text=True,
    )

    instances = [json.loads(line) for line in result.stdout.splitlines()]
    assert [item["address"] for item in instances] == [
        "azurerm_private_dns_zone.mysql",
        "azurerm_private_dns_zone_virtual_network_link.mysql_operator[0]",
        'module.azure_openai_private_endpoint.azurerm_private_dns_zone_virtual_network_link.extra["runner"]',
    ]
    assert instances[1]["attributes"]["id"] == "link-id"
    workflow = WORKFLOW.read_text(encoding="utf-8")
    assert workflow.count("terraform show -json") == 1
    assert 'terraform show -json "$plan_file"' in workflow
    assert workflow.count("terraform state pull | jq -c -f") == 5
    # jq 1.6 sets -e from the last streamed input only, so fail-closed reads slurp the stream.
    assert workflow.count("jq -s -er '\n            .[] | select(") == 3


READBACK = runpy.run_path(str(LAB_SCRIPTS / "readback_store_demo.py"))
HOST = "fdai-store-lab-krc-0a1b2c.koreacentral.cloudapp.azure.com"
LB_IP = "203.0.113.10"


def _workload(kind: str, name: str, replicas: int, ready: int | None = None) -> dict:
    ready = replicas if ready is None else ready
    return {
        "kind": kind,
        "metadata": {"name": name, "generation": 2},
        "spec": {"replicas": replicas},
        "status": {
            "observedGeneration": 2,
            "readyReplicas": ready,
            "availableReplicas": ready,
            "updatedReplicas": replicas,
        },
    }


def _kube(**overrides: Any) -> dict:
    pinned = sorted(READBACK["pinned_images"]())
    workloads = [
        _workload(kind, name, replicas)
        for (kind, name), replicas in READBACK["EXPECTED_WORKLOADS"].items()
    ]
    services = [
        {
            "kind": "Service",
            "metadata": {
                "name": "store-front",
                "annotations": {
                    "service.beta.kubernetes.io/azure-dns-label-name": HOST.split(".")[0]
                },
            },
            "spec": {"type": "LoadBalancer"},
            "status": {"loadBalancer": {"ingress": [{"ip": LB_IP}]}},
        },
        {"kind": "Service", "metadata": {"name": "store-admin"}, "spec": {"type": "ClusterIP"}},
    ]
    pods = [
        {
            "kind": "Pod",
            "metadata": {"name": f"pod-{index}", "labels": {"app": f"app-{index}"}},
            "spec": {"containers": [{"name": "main", "image": image}]},
            "status": {
                "phase": "Running",
                "containerStatuses": [{"name": "main", "imageID": f"docker.io/x{image[-72:]}"}],
            },
        }
        for index, image in enumerate(overrides.pop("images", pinned))
    ]
    items = workloads + services + pods + overrides.pop("extra", [])
    return {"kind": "List", "items": items}


def _evaluate(kube: dict | None = None, **overrides: Any) -> list[str]:
    arguments = {
        "kube": kube or _kube(),
        "public_ips": [{"ipAddress": LB_IP, "fqdn": HOST}],
        "dns_addresses": [LB_IP],
        "http_status": 200,
        "hostname": HOST,
        "dns_label": HOST.split(".")[0],
        "pinned": READBACK["pinned_images"](),
    }
    arguments.update(overrides)
    _, failures = READBACK["evaluate"](**arguments)
    return failures


def test_store_demo_readback_verifies_every_required_observation() -> None:
    assert _evaluate() == []

    kube = _kube()
    kube["items"][2]["status"]["readyReplicas"] = 2
    assert "workload_not_ready:Deployment/order-service" in _evaluate(kube)
    exposed = _kube()
    exposed["items"][10]["spec"]["type"] = "LoadBalancer"
    assert "store_admin_not_private" in _evaluate(exposed)
    assert "unexpected_exposed_service:store-admin" in _evaluate(exposed)
    tagged = _kube(images=["ghcr.io/azure-samples/aks-store-demo/order-service:2.2.0"])
    assert "unpinned_image:app-0/main" in _evaluate(tagged)
    extra = _kube(extra=[_workload("Deployment", "api-backend", 1)])
    assert "unexpected_workload:Deployment/api-backend" in _evaluate(extra)
    assert "dns_does_not_resolve_to_load_balancer" in _evaluate(dns_addresses=["198.51.100.7"])
    assert "azure_public_ip_mismatch" in _evaluate(public_ips=[])
    assert "store_front_health_failed" in _evaluate(http_status=503)


def test_store_demo_readback_detects_a_running_digest_that_differs() -> None:
    kube = _kube()
    pod = next(item for item in kube["items"] if item["kind"] == "Pod")
    pod["status"]["containerStatuses"][0]["imageID"] = "docker.io/x@sha256:" + "0" * 64

    assert "image_digest_mismatch:app-0/main" in _evaluate(kube)


def test_store_demo_readback_cli_retains_a_repository_safe_document(tmp_path: Path) -> None:
    output = tmp_path / "readback.json"
    responses = {"kubectl": _kube(), "aks": "MC_rg-lab-example_aks-store-demo_koreacentral"}

    def run(command: Sequence[str]) -> Any:
        if command[0] == "kubectl":
            return responses["kubectl"]
        if command[1] == "aks":
            return responses["aks"]
        return [{"ipAddress": LB_IP, "fqdn": HOST}]

    arguments = [
        "--output",
        str(output),
        "--store-front-url",
        f"http://{HOST}",
        "--resource-group",
        RG,
        "--cluster-name",
        "aks-store-demo",
        "--source-commit",
        "a" * 40,
        "--run-id",
        "123",
        "--run-attempt",
        "1",
    ]

    status = READBACK["main"](
        arguments,
        run=run,
        resolver=lambda _: [LB_IP],
        prober=lambda _: 200,
        sleep=lambda _: None,
    )

    document = json.loads(output.read_text(encoding="utf-8"))
    assert status == 0
    assert document["verdict"] == "verified"
    assert document["store_front"]["load_balancer_ip"] == LB_IP
    assert document["store_front"]["http_health_status"] == 200
    assert document["store_admin"] == {"service_type": "ClusterIP", "external_ingress": []}
    retained_text = output.read_text(encoding="utf-8")
    assert not any(word in retained_text for word in ("kubeconfig", "password", "token"))
    failed = READBACK["main"](
        arguments,
        run=run,
        resolver=lambda _: [],
        prober=lambda _: None,
        sleep=lambda _: None,
    )
    assert failed == 1
    assert json.loads(output.read_text(encoding="utf-8"))["verdict"] == "failed"
    bad_url = [*arguments[:3], "http://example.com", *arguments[4:]]
    assert READBACK["main"](bad_url, run=run) == 2
