schema_version: 1.0.0
id: azure-builtin.container-registry.configure-container-registries-to-disable-arm-audience-token-authentication
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: container-registry
check_logic:
  kind: expression
  reference: azure-policy://785596ed-054f-41bc-aaec-7f3d0ba05725
remediation:
  template_ref: remediation/azure-builtin/785596ed-054f-41bc-aaec-7f3d0ba05725.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 785596ed-054f-41bc-aaec-7f3d0ba05725
  azure_policy_display_name: Configure container registries to disable ARM audience
    token authentication.
  azure_policy_effect_default: Modify
  azure_policy_category: Container Registry
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Container
    Registry/ACR_AADAuthenticationAsArmDisabled_Modify.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
