schema_version: 1.0.0
id: azure-builtin.azure.containerinstance.containergroups.configure-diagnostics-for-container-group-to-log-analytics-workspace
version: 1.0.0
source: azure_policy
severity: low
category: security
resource_type: azure.containerinstance.containergroups
check_logic:
  kind: expression
  reference: azure-policy://21c469fa-a887-4363-88a9-60bfd6911a15
remediation:
  template_ref: remediation/azure-builtin/21c469fa-a887-4363-88a9-60bfd6911a15.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 21c469fa-a887-4363-88a9-60bfd6911a15
  azure_policy_display_name: Configure diagnostics for container group to log analytics
    workspace
  azure_policy_effect_default: Append
  azure_policy_category: Container Instances
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Container
    Instances/ContainerInstance_LogAnalytics_Append.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
