schema_version: 1.0.0
id: azure-builtin.azure.synapse.workspaces.configure-microsoft-defender-for-sql-to-be-enabled-on-synapse-workspaces
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: azure.synapse.workspaces
check_logic:
  kind: expression
  reference: azure-policy://951c1558-50a5-4ca3-abb6-a93e3e2367a6
remediation:
  template_ref: remediation/azure-builtin/951c1558-50a5-4ca3-abb6-a93e3e2367a6.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 951c1558-50a5-4ca3-abb6-a93e3e2367a6
  azure_policy_display_name: Configure Microsoft Defender for SQL to be enabled on
    Synapse workspaces
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Security Center
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Security
    Center/TdOnSynapseWorkspaces_DINE.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:714665c9b0d276b81b54dd8fc692a03993877c1ea08c958d867e0aa2386bec81
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-10-08T09:14:46Z'
