schema_version: 1.0.0
id: azure-builtin.compute.vm.deprecated-configure-association-to-link-virtual-machines-to-user-defined-microsoft-defender-for-clo
version: 2.0.1
source: azure_policy
severity: medium
category: security
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://9c0aa188-e5fe-4569-8f74-b6e155624d9a
remediation:
  template_ref: remediation/azure-builtin/9c0aa188-e5fe-4569-8f74-b6e155624d9a.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 9c0aa188-e5fe-4569-8f74-b6e155624d9a
  azure_policy_display_name: '[Deprecated]: Configure Association to link virtual
    machines to user-defined Microsoft Defender for Cloud Data Collection Rule'
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Security Center
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Security
    Center/ASC_AMA_UserWorkspacePipeline_DCRA_DINE.json
  source_version: 2.0.1
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:3033624aafe7b0c630ec95857d2069b0cbec716c872fbc86db11be00dd8db27f
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-10-08T09:14:46Z'
