schema_version: 1.0.0
id: azure-builtin.azure.signalrservice.webpubsub.configure-azure-web-pubsub-service-to-disable-local-authentication
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: azure.signalrservice.webpubsub
check_logic:
  kind: expression
  reference: azure-policy://17f9d984-90c8-43dd-b7a6-76cb694815c1
remediation:
  template_ref: remediation/azure-builtin/17f9d984-90c8-43dd-b7a6-76cb694815c1.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 17f9d984-90c8-43dd-b7a6-76cb694815c1
  azure_policy_display_name: Configure Azure Web PubSub Service to disable local authentication
  azure_policy_effect_default: Modify
  azure_policy_category: Web PubSub
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Web
    PubSub/DisableLocalAuth_Modify.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
