schema_version: 1.0.0
id: azure-builtin.compute.vm.configure-backup-on-virtual-machines-without-a-given-tag-to-a-new-recovery-services-vault-with-a-def
version: 9.5.0
source: azure_policy
severity: medium
category: reliability
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://98d0b9f8-fd90-49c9-88e2-d3baf3b0dd86
remediation:
  template_ref: remediation/azure-builtin/98d0b9f8-fd90-49c9-88e2-d3baf3b0dd86.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 98d0b9f8-fd90-49c9-88e2-d3baf3b0dd86
  azure_policy_display_name: Configure backup on virtual machines without a given
    tag to a new recovery services vault with a default policy
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Backup
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Backup/VirtualMachineApplicationCentricBackup_DINE_WithOutTag.json
  source_version: 9.5.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
