schema_version: 1.0.0
id: azure-builtin.compute.vm.configure-backup-on-virtual-machines-with-a-given-tag-to-an-existing-recovery-services-vault-in-the
version: 9.5.0
source: azure_policy
severity: medium
category: reliability
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://345fa903-145c-4fe1-8bcd-93ec2adccde8
remediation:
  template_ref: remediation/azure-builtin/345fa903-145c-4fe1-8bcd-93ec2adccde8.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 345fa903-145c-4fe1-8bcd-93ec2adccde8
  azure_policy_display_name: Configure backup on virtual machines with a given tag
    to an existing recovery services vault in the same location
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Backup
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Backup/VirtualMachineWithTag_DINE.json
  source_version: 9.5.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
