schema_version: 1.0.0
id: azure-builtin.azure.recoveryservices.vaults.preview-configure-azure-recovery-services-vaults-to-disable-public-network-access
version: 1.0.0
source: azure_policy
severity: medium
category: reliability
resource_type: azure.recoveryservices.vaults
check_logic:
  kind: expression
  reference: azure-policy://04726aae-4e8d-427c-af7d-ecf56d490022
remediation:
  template_ref: remediation/azure-builtin/04726aae-4e8d-427c-af7d-ecf56d490022.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 04726aae-4e8d-427c-af7d-ecf56d490022
  azure_policy_display_name: '[Preview]: Configure Azure Recovery Services vaults
    to disable public network access'
  azure_policy_effect_default: Modify
  azure_policy_category: Backup
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Backup/RecoveryServices_PublicNetworkAccess_Modify.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
