"""The default FDAI capability catalog (customer-agnostic).

Enumerates the control-plane capabilities the console surfaces, including
the ones added for the SRE-agent parity slides (8-20). Entries are inert
metadata; ``side_effect_class`` and ``default_mode`` describe safety, they
do not grant it.
"""

from __future__ import annotations

from fdai.core.capability_catalog.catalog import (
    Capability,
    CapabilityCatalog,
    CapabilityCategory,
    CapabilityParity,
    SideEffectClass,
)
from fdai.shared.contracts.models import Mode

_CAPABILITIES: tuple[Capability, ...] = (
    Capability(
        capability_id="knowledge.register",
        name="Register knowledge + code sources",
        category=CapabilityCategory.KNOWLEDGE,
        summary="Connect knowledge documents and code repositories to ground analysis.",
        side_effect_class=SideEffectClass.EXECUTE,
        default_mode=Mode.SHADOW,
        required_role="contributor",
        slide_ref="8",
        tags=("rag", "code-access"),
    ),
    Capability(
        capability_id="chaos.run_experiment",
        name="Run a fault-injection experiment",
        category=CapabilityCategory.CHAOS,
        summary="Validate detect->mitigate with a governed, reversible fault injection.",
        side_effect_class=SideEffectClass.EXECUTE,
        default_mode=Mode.SHADOW,
        required_role="approver",
        slide_ref="9",
        tags=("resilience", "hil"),
    ),
    Capability(
        capability_id="investigation.run",
        name="Investigate across resources",
        category=CapabilityCategory.INVESTIGATION,
        summary="On-demand cross-resource investigation producing RCA + P1..P3 recommendations.",
        side_effect_class=SideEffectClass.READ,
        default_mode=Mode.SHADOW,
        required_role="reader",
        slide_ref="10-14",
        tags=("rca", "timeline"),
    ),
    Capability(
        capability_id="investigation.report",
        name="Investigation report",
        category=CapabilityCategory.REPORTING,
        summary="Timeline + correlation + prioritized recommendations within a latency budget.",
        side_effect_class=SideEffectClass.READ,
        required_role="reader",
        slide_ref="13-14",
        tags=("report",),
    ),
    Capability(
        capability_id="incident.create",
        name="Create an incident",
        category=CapabilityCategory.INCIDENT,
        summary=(
            "Prepare and confirm an incident with severity and correlation; "
            "audit it and notify subscribers."
        ),
        side_effect_class=SideEffectClass.EXECUTE,
        default_mode=Mode.SHADOW,
        required_role="contributor",
        slide_ref="15",
        tags=("gitops", "handoff"),
    ),
    Capability(
        capability_id="scheduler.create_task",
        name="Create a scheduled monitoring task",
        category=CapabilityCategory.SCHEDULING,
        summary="Create a recurring monitoring job that re-enters the control loop.",
        side_effect_class=SideEffectClass.EXECUTE,
        default_mode=Mode.SHADOW,
        required_role="contributor",
        slide_ref="16",
        tags=("scheduler",),
    ),
    Capability(
        capability_id="irp.author",
        name="Author an incident response plan",
        category=CapabilityCategory.RESPONSE_PLAN,
        summary="Author a gated response plan and pretest it against similar incidents.",
        side_effect_class=SideEffectClass.SIMULATE,
        required_role="contributor",
        slide_ref="17",
        tags=("irp", "pretest"),
    ),
    Capability(
        capability_id="irp.respond",
        name="Respond to an alert (IRP)",
        category=CapabilityCategory.RESPONSE_PLAN,
        summary="Alert -> budgeted investigation -> proposed mitigation -> HIL -> notify.",
        side_effect_class=SideEffectClass.APPROVE,
        required_role="approver",
        slide_ref="18",
        tags=("irp", "hil", "chatops"),
    ),
    Capability(
        capability_id="cost.metering",
        name="Usage + cost metering",
        category=CapabilityCategory.COST,
        summary="Token-to-cost rollups per conversation, day, and month.",
        side_effect_class=SideEffectClass.READ,
        required_role="reader",
        slide_ref="21",
        tags=("finops", "aau"),
    ),
)

_TOOLS = "https://learn.microsoft.com/azure/sre-agent/tools"
_DIAGNOSE = "https://learn.microsoft.com/azure/sre-agent/diagnose-azure-observability"
_MEMORY = "https://learn.microsoft.com/azure/sre-agent/memory"
_INCIDENTS = "https://learn.microsoft.com/azure/sre-agent/incident-platforms"
_PLANS = "https://learn.microsoft.com/azure/sre-agent/incident-response-plans"
_SCHEDULES = "https://learn.microsoft.com/azure/sre-agent/scheduled-tasks"
_WORKFLOWS = "https://learn.microsoft.com/azure/sre-agent/workflow-automation"


def _parity(
    capability_id: str,
    name: str,
    category: CapabilityCategory,
    summary: str,
    source: str,
    evidence: tuple[str, ...],
    *,
    side_effect: SideEffectClass = SideEffectClass.READ,
    status: CapabilityParity = CapabilityParity.NATIVE,
    role: str = "reader",
) -> Capability:
    return Capability(
        capability_id=capability_id,
        name=name,
        category=category,
        summary=summary,
        side_effect_class=side_effect,
        required_role=role,
        tags=("sre-parity",),
        parity=status,
        official_source=source,
        evidence_refs=evidence,
    )


_SRE_PARITY_CAPABILITIES: tuple[Capability, ...] = (
    _parity(
        "observability.resource-discovery",
        "Discover Azure resources",
        CapabilityCategory.DETECTION,
        "Discover bounded Azure inventory across configured scopes.",
        _DIAGNOSE,
        ("src/fdai/delivery/azure/inventory.py",),
    ),
    _parity(
        "observability.topology",
        "Map application topology",
        CapabilityCategory.INVESTIGATION,
        "Project resource relationships and dependency paths.",
        _DIAGNOSE,
        (
            "src/fdai/delivery/read_api/routes/inventory_graph.py",
            "src/fdai/core/rca/causal_chain.py",
        ),
    ),
    _parity(
        "observability.activity-log",
        "Read Azure activity changes",
        CapabilityCategory.INVESTIGATION,
        "Read and correlate administrative changes and deployments.",
        _DIAGNOSE,
        ("src/fdai/delivery/azure/activity_log.py",),
    ),
    _parity(
        "observability.log-query",
        "Query Log Analytics",
        CapabilityCategory.INVESTIGATION,
        "Run bounded single-workspace KQL and render verified rows.",
        _DIAGNOSE,
        (
            "src/fdai/delivery/azure/log_query.py",
            "src/fdai/delivery/read_api/routes/chat_log_query.py",
        ),
    ),
    _parity(
        "observability.trace-query",
        "Trace distributed requests",
        CapabilityCategory.INVESTIGATION,
        "Project AppRequests and AppDependencies into typed RCA spans.",
        _DIAGNOSE,
        ("src/fdai/delivery/azure/telemetry_query.py", "src/fdai/shared/providers/trace_query.py"),
    ),
    _parity(
        "observability.metric-query",
        "Query Azure Monitor metrics",
        CapabilityCategory.DETECTION,
        "Route metric reads across Prometheus, Metrics API, and KQL.",
        _DIAGNOSE,
        ("src/fdai/composition/wire_metric_provider.py",),
    ),
    _parity(
        "observability.metric-discovery",
        "Resolve supported metrics",
        CapabilityCategory.DETECTION,
        "Select the fastest configured backend for each known metric.",
        _DIAGNOSE,
        (
            "src/fdai/shared/providers/routed_metric.py",
            "src/fdai/delivery/azure/metrics_api_queries.py",
        ),
    ),
    _parity(
        "observability.trend-analysis",
        "Analyze trends and anomalies",
        CapabilityCategory.DETECTION,
        "Detect anomaly, forecast, and composite multi-signal conditions.",
        _DIAGNOSE,
        ("src/fdai/core/detection/anomaly.py", "src/fdai/core/detection/forecast.py"),
    ),
    _parity(
        "observability.deep-diagnostics",
        "Run resource diagnostics",
        CapabilityCategory.INVESTIGATION,
        "Use resource analyzers plus governed Python and shell task artifacts.",
        _DIAGNOSE,
        ("src/fdai/core/investigation/analyzers.py", "src/fdai/core/python_task/"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "operations.azure-cli-read",
        "Run typed Azure reads",
        CapabilityCategory.INVESTIGATION,
        "Execute cataloged Azure reads with exact argv and trusted subscription scope.",
        _TOOLS,
        ("src/fdai/delivery/azure/command_runner.py", "src/fdai/core/tools/default_commands.py"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "operations.typed-mutation",
        "Apply governed Azure changes",
        CapabilityCategory.REMEDIATION,
        "Replace arbitrary write CLI with ActionType, dry-run, lock, rollback, "
        "risk, and audit gates.",
        _TOOLS,
        ("src/fdai/core/executor/", "src/fdai/core/risk_gate/"),
        side_effect=SideEffectClass.EXECUTE,
        status=CapabilityParity.SAFER_ALTERNATIVE,
        role="approver",
    ),
    _parity(
        "operations.kubectl",
        "Run governed Kubernetes operations",
        CapabilityCategory.REMEDIATION,
        "Run cataloged kubectl diagnostics and promoted direct actions.",
        _TOOLS,
        (
            "src/fdai/delivery/remediation/live_direct_api.py",
            "src/fdai/delivery/chaos/live_injectors.py",
        ),
        side_effect=SideEffectClass.EXECUTE,
        status=CapabilityParity.SAFER_ALTERNATIVE,
        role="approver",
    ),
    _parity(
        "investigation.cross-source",
        "Correlate cross-source evidence",
        CapabilityCategory.INVESTIGATION,
        "Combine inventory, telemetry, changes, audit, and knowledge citations.",
        _DIAGNOSE,
        ("src/fdai/core/rca/evidence.py", "src/fdai/core/rca/change_evidence.py"),
    ),
    _parity(
        "investigation.parallel",
        "Run independent diagnostics concurrently",
        CapabilityCategory.INVESTIGATION,
        "Bound concurrent analyzers and isolated task workers.",
        _TOOLS,
        ("src/fdai/core/investigation/coordinator.py", "src/fdai/core/task_worker/runtime.py"),
    ),
    _parity(
        "investigation.delegation",
        "Delegate bounded exploration",
        CapabilityCategory.INVESTIGATION,
        "Delegate depth-one read tasks with attenuated tool capabilities.",
        _TOOLS,
        ("src/fdai/core/task_worker/",),
    ),
    _parity(
        "investigation.background",
        "Continue long investigations",
        CapabilityCategory.INVESTIGATION,
        "Persist bounded detached investigation state with cancellation and completion handoff.",
        _TOOLS,
        ("src/fdai/core/background_task/",),
    ),
    _parity(
        "incident.platform-reception",
        "Receive external incidents",
        CapabilityCategory.INCIDENT,
        "Poll bounded incident sources and publish stable idempotent events.",
        _INCIDENTS,
        ("src/fdai/core/incident/platform_sync.py",),
    ),
    _parity(
        "incident.platform-writeback",
        "Update external incidents",
        CapabilityCategory.INCIDENT,
        "Acknowledge, resolve, and add notes through injected PagerDuty or ServiceNow adapters.",
        _INCIDENTS,
        ("src/fdai/delivery/incident_platform/",),
        side_effect=SideEffectClass.EXECUTE,
        status=CapabilityParity.EXTERNAL_BINDING,
        role="approver",
    ),
    _parity(
        "incident.rich-card",
        "Render rich incident cards",
        CapabilityCategory.INCIDENT,
        "Render severity, status, action, and evidence in Teams and Slack cards.",
        _INCIDENTS,
        (
            "src/fdai/delivery/chatops/teams_adapter.py",
            "src/fdai/delivery/chatops/slack_adapter.py",
        ),
    ),
    _parity(
        "incident.response-filter",
        "Filter incident response plans",
        CapabilityCategory.RESPONSE_PLAN,
        "Compile event triggers, principal bindings, and enabled workflow definitions.",
        _PLANS,
        ("src/fdai/core/workflow/trigger_index.py", "src/fdai/core/workflow/definition.py"),
    ),
    _parity(
        "incident.specialist-routing",
        "Route incidents to specialists",
        CapabilityCategory.RESPONSE_PLAN,
        "Route typed owned-object work to fixed accountable Pantheon specialists.",
        _PLANS,
        ("src/fdai/agents/_framework/pantheon.py",),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "incident.run-mode",
        "Select review or autonomous mode",
        CapabilityCategory.RESPONSE_PLAN,
        "Derive autonomy from promotion, policy, risk, evidence, and role "
        "instead of a yolo toggle.",
        _PLANS,
        ("src/fdai/core/risk_gate/ceiling.py", "src/fdai/core/risk_gate/gate.py"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "knowledge.document-search",
        "Search operational documents",
        CapabilityCategory.KNOWLEDGE,
        "Index and retrieve runbooks, architecture guides, and procedures with citations.",
        _MEMORY,
        ("src/fdai/delivery/document_index/", "src/fdai/core/knowledge/"),
    ),
    _parity(
        "knowledge.past-incidents",
        "Reuse past incident patterns",
        CapabilityCategory.KNOWLEDGE,
        "Retrieve and reverify similar resolved incidents through T1.",
        _MEMORY,
        (
            "src/fdai/core/tiers/t1_lightweight/",
            "src/fdai/delivery/persistence/pgvector_pattern_library.py",
        ),
    ),
    _parity(
        "knowledge.user-memory",
        "Store confirmed operator facts",
        CapabilityCategory.KNOWLEDGE,
        "Persist principal-scoped confirmed facts with provenance and expiry.",
        _MEMORY,
        (
            "src/fdai/shared/providers/user_context.py",
            "src/fdai/delivery/persistence/postgres_user_context.py",
        ),
    ),
    _parity(
        "knowledge.auto-learning",
        "Learn from completed work",
        CapabilityCategory.KNOWLEDGE,
        "Run consent-gated post-turn review and inert proposal generation.",
        _MEMORY,
        ("src/fdai/core/learning/", "src/fdai/runtime/post_turn_review.py"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "knowledge.resource-priority",
        "Prioritize same-resource evidence",
        CapabilityCategory.KNOWLEDGE,
        "Scope memory, pattern, and incident retrieval to the active resource.",
        _MEMORY,
        ("src/fdai/core/operator_memory/types.py", "src/fdai/core/rca/"),
    ),
    _parity(
        "knowledge.graph",
        "Build persistent knowledge graph",
        CapabilityCategory.KNOWLEDGE,
        "Project ontology objects and links into durable PostgreSQL state.",
        _MEMORY,
        ("src/fdai/delivery/persistence/postgres_ontology.py", "src/fdai/shared/ontology/"),
    ),
    _parity(
        "knowledge.tsg",
        "Retrieve troubleshooting guides",
        CapabilityCategory.KNOWLEDGE,
        "Ingest governed wiki and document sources through the knowledge seam.",
        _MEMORY,
        ("src/fdai/core/knowledge/models.py", "src/fdai/delivery/knowledge/loader.py"),
        status=CapabilityParity.EXTERNAL_BINDING,
    ),
    _parity(
        "devops.github",
        "Read and write GitHub operations",
        CapabilityCategory.KNOWLEDGE,
        "Read deployment changes and deliver governed PR, issue, and workflow operations.",
        _TOOLS,
        ("src/fdai/delivery/github/", "src/fdai/delivery/gitops_pr/"),
        status=CapabilityParity.EXTERNAL_BINDING,
    ),
    _parity(
        "devops.azure-devops",
        "Read Azure DevOps changes",
        CapabilityCategory.KNOWLEDGE,
        "Read normalized Azure DevOps change evidence and deliver through the PR seam.",
        _TOOLS,
        ("src/fdai/delivery/azure_devops/change_feed.py",),
        status=CapabilityParity.EXTERNAL_BINDING,
    ),
    _parity(
        "extensibility.kusto",
        "Create bounded Kusto capabilities",
        CapabilityCategory.KNOWLEDGE,
        "Use trusted metric KQL templates and bounded explicit Command Deck KQL.",
        _TOOLS,
        (
            "src/fdai/delivery/azure/demo_queries.py",
            "src/fdai/delivery/read_api/routes/chat_log_query.py",
        ),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "extensibility.python",
        "Run governed Python tasks",
        CapabilityCategory.KNOWLEDGE,
        "Validate inert multi-file artifacts before isolated execution planning.",
        _TOOLS,
        ("src/fdai/core/python_task/", "src/fdai/core/programmatic_pipeline/"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "extensibility.shell",
        "Run governed shell tasks",
        CapabilityCategory.KNOWLEDGE,
        "Validate shell artifacts and execute only in registered sandbox profiles.",
        _TOOLS,
        (
            "src/fdai/core/python_task/shell_validator.py",
            "src/fdai/delivery/shell/bubblewrap_runner.py",
        ),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "extensibility.mcp",
        "Connect MCP tools",
        CapabilityCategory.KNOWLEDGE,
        "Discover, govern, and execute MCP tools through catalog and management adapters.",
        _TOOLS,
        ("src/fdai/delivery/mcp/",),
    ),
    _parity(
        "extensibility.link",
        "Generate evidence links",
        CapabilityCategory.KNOWLEDGE,
        "Carry bounded evidence and source references instead of executable browser templates.",
        _TOOLS,
        ("src/fdai/core/rca/contract.py", "src/fdai/delivery/read_api/routes/chat_verification.py"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "extensibility.http",
        "Call governed HTTP tools",
        CapabilityCategory.KNOWLEDGE,
        "Use registered MCP, webhook, and ToolExecutor adapters with server-owned authentication.",
        _TOOLS,
        ("src/fdai/delivery/mcp/executor.py", "src/fdai/delivery/notifications/webhook.py"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "communication.teams",
        "Send Teams updates",
        CapabilityCategory.REPORTING,
        "Send signed contextual cards and threaded replies.",
        _TOOLS,
        ("src/fdai/delivery/notifications/teams.py", "src/fdai/delivery/channels/teams.py"),
        status=CapabilityParity.EXTERNAL_BINDING,
    ),
    _parity(
        "communication.email",
        "Send email reports",
        CapabilityCategory.REPORTING,
        "Send reports and stakeholder briefings through the email channel.",
        _TOOLS,
        ("src/fdai/delivery/notifications/email.py", "src/fdai/core/notifications/briefing.py"),
        status=CapabilityParity.EXTERNAL_BINDING,
    ),
    _parity(
        "scheduling.lifecycle",
        "Manage scheduled tasks",
        CapabilityCategory.SCHEDULING,
        "Create, pause, resume, edit, run now, cancel, persist, and inspect tasks.",
        _SCHEDULES,
        ("src/fdai/core/scheduler/", "src/fdai/delivery/persistence/postgres_scheduler_store.py"),
    ),
    _parity(
        "scheduling.history",
        "Inspect scheduled executions",
        CapabilityCategory.SCHEDULING,
        "Record idempotent dispatch attempts and expose bounded run history.",
        _SCHEDULES,
        ("src/fdai/core/scheduler/run_ledger.py", "src/fdai/core/scheduler/history.py"),
    ),
    _parity(
        "automation.workflow",
        "Author governed workflows",
        CapabilityCategory.RESPONSE_PLAN,
        "Validate versioned workflow definitions and execute through the normal action pipeline.",
        _WORKFLOWS,
        ("src/fdai/core/workflow/", "src/fdai/delivery/read_api/routes/workflow_authoring.py"),
    ),
    _parity(
        "automation.specialists",
        "Use specialized agents",
        CapabilityCategory.RESPONSE_PLAN,
        "Use a fixed role-invariant 15-agent Pantheon plus governed skills and bundles.",
        _WORKFLOWS,
        ("src/fdai/agents/_framework/pantheon.py", "src/fdai/core/skills/"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "reporting.visualization",
        "Generate charts and dashboards",
        CapabilityCategory.REPORTING,
        "Render declarative time-series, chart, heatmap, flow, and reliability widgets.",
        _TOOLS,
        ("src/fdai/core/reporting/widgets/",),
    ),
    _parity(
        "reporting.pdf",
        "Generate PDF reports",
        CapabilityCategory.REPORTING,
        "Encode print-quality reports with the optional PDF runtime.",
        _TOOLS,
        ("src/fdai/delivery/reporting/pdf_format.py",),
    ),
    _parity(
        "measurement.slo",
        "Measure SLO error budgets",
        CapabilityCategory.REPORTING,
        "Evaluate multi-window burn rates and publish breach events.",
        _DIAGNOSE,
        ("src/fdai/core/slo/",),
    ),
    _parity(
        "measurement.dora",
        "Measure DORA outcomes",
        CapabilityCategory.REPORTING,
        "Compute deployment frequency, lead time, change failure, and recovery distributions.",
        _WORKFLOWS,
        ("src/fdai/core/measurement/dora.py",),
    ),
    _parity(
        "paging.on-call",
        "Resolve on-call responders",
        CapabilityCategory.INCIDENT,
        "Resolve schedule-aware escalation targets with fail-safe fallback.",
        _INCIDENTS,
        (
            "src/fdai/core/oncall/resolver.py",
            "src/fdai/delivery/incident_platform/pagerduty_oncall.py",
        ),
        status=CapabilityParity.EXTERNAL_BINDING,
    ),
    _parity(
        "paging.pagerduty",
        "Page PagerDuty",
        CapabilityCategory.INCIDENT,
        "Trigger deduplicated operational paging and synchronize incident lifecycle.",
        _INCIDENTS,
        (
            "src/fdai/delivery/notifications/pagerduty.py",
            "src/fdai/delivery/incident_platform/pagerduty.py",
        ),
        status=CapabilityParity.EXTERNAL_BINDING,
    ),
    _parity(
        "safety.human-approval",
        "Require risk-based approval",
        CapabilityCategory.REMEDIATION,
        "Require deterministic eligibility, risk, role, and approval gates "
        "instead of global auto-approval.",
        _PLANS,
        ("src/fdai/core/risk_gate/", "src/fdai/core/hil_resume/"),
        status=CapabilityParity.SAFER_ALTERNATIVE,
    ),
    _parity(
        "audit.append-only",
        "Record complete operational evidence",
        CapabilityCategory.REPORTING,
        "Write every terminal path to append-only hash-chained audit state.",
        _WORKFLOWS,
        ("src/fdai/core/audit/",),
    ),
)


def default_capability_catalog() -> CapabilityCatalog:
    """Return the customer-agnostic default capability catalog."""
    return CapabilityCatalog((*_CAPABILITIES, *_SRE_PARITY_CAPABILITIES))


__all__ = ["default_capability_catalog"]
