"""Bounded, provider-neutral read-investigation planning."""

from fdai.core.read_investigation.adaptive import (
    AdaptiveHypothesisReviser,
    AdaptiveInvestigationCoordinator,
    AdaptiveRoundProposal,
    AdaptiveRoundSource,
    AdaptiveShadowComparisonSink,
    VerifiedObservationGateway,
)
from fdai.core.read_investigation.adaptive_codec import (
    adaptive_result_from_mapping,
    adaptive_result_to_mapping,
)
from fdai.core.read_investigation.adaptive_contract import (
    ADAPTIVE_SESSION_REDUCER_VERSION,
    AdaptiveInvestigationBudget,
    AdaptiveInvestigationDisposition,
    AdaptiveInvestigationIteration,
    AdaptiveInvestigationResult,
    AdaptiveObservationExecution,
    HypothesisRevisionSet,
    VerifiedObservationPlanBinding,
    build_adaptive_investigation_iteration,
    build_adaptive_investigation_result,
    build_adaptive_observation_execution,
    build_hypothesis_revision_set,
    build_verified_observation_plan_binding,
)
from fdai.core.read_investigation.adaptive_process import (
    ADAPTIVE_INVESTIGATION_WORKFLOW_REF,
    ADAPTIVE_INVESTIGATION_WORKFLOW_VERSION,
    AdaptiveInvestigationProcessRecorder,
    AdaptiveInvestigationProcessStart,
    project_adaptive_investigation_room,
)
from fdai.core.read_investigation.catalog import (
    READ_TOOL_SPECS,
    LatencyClass,
    ReadToolSpec,
    read_tool_spec,
)
from fdai.core.read_investigation.execution_policy import (
    InvestigationExecutionPolicy,
    ReadInvestigationExecutionMode,
    interactive_investigation_policy,
)
from fdai.core.read_investigation.idempotency import (
    MAX_READ_INVESTIGATION_ATTEMPTS,
    InMemoryReadInvestigationRunStore,
    ReadInvestigationRunConflictError,
    ReadInvestigationRunLease,
    ReadInvestigationRunMode,
    ReadInvestigationRunRecord,
    ReadInvestigationRunState,
    ReadInvestigationRunStore,
    ReadInvestigationRunUsage,
    read_investigation_request_digest,
    read_investigation_request_projection,
    read_investigation_run_id,
)
from fdai.core.read_investigation.intent_spec import (
    READ_INVESTIGATION_INTENT_SPECS,
    ReadInvestigationIntentSpec,
    read_investigation_intent_spec,
)
from fdai.core.read_investigation.interactive import (
    InMemoryReadInvestigationRunProgressStore,
    InteractiveReadInvestigationConfig,
    InteractiveReadInvestigationCoordinator,
    InteractiveReadInvestigationSubmission,
    ReadInvestigationRunProgress,
    ReadInvestigationRunProgressStore,
)
from fdai.core.read_investigation.latency import (
    PlanLatencyEstimate,
    ReadLatencyProfile,
    estimate_parallel_p95,
    estimate_plan_latency,
    estimate_sequential_p95,
    latency_profile,
)
from fdai.core.read_investigation.mode_selector import ReadInvestigationModeSelector
from fdai.core.read_investigation.models import (
    ReadInvestigationBudget,
    ReadInvestigationOutcome,
    ReadInvestigationPlan,
    ReadInvestigationRequest,
    ReadInvestigationResult,
    ReadInvestigationStep,
)
from fdai.core.read_investigation.planner import plan_read_investigation
from fdai.core.read_investigation.progress import ReadInvestigationProgressKind
from fdai.core.read_investigation.routing import resource_name_from_question
from fdai.core.read_investigation.service import ReadInvestigationService

__all__ = [
    "ADAPTIVE_INVESTIGATION_WORKFLOW_REF",
    "ADAPTIVE_INVESTIGATION_WORKFLOW_VERSION",
    "ADAPTIVE_SESSION_REDUCER_VERSION",
    "AdaptiveHypothesisReviser",
    "AdaptiveInvestigationBudget",
    "AdaptiveInvestigationCoordinator",
    "AdaptiveInvestigationDisposition",
    "AdaptiveInvestigationIteration",
    "AdaptiveInvestigationProcessRecorder",
    "AdaptiveInvestigationProcessStart",
    "AdaptiveInvestigationResult",
    "AdaptiveObservationExecution",
    "AdaptiveRoundProposal",
    "AdaptiveRoundSource",
    "AdaptiveShadowComparisonSink",
    "READ_TOOL_SPECS",
    "LatencyClass",
    "InvestigationExecutionPolicy",
    "interactive_investigation_policy",
    "InMemoryReadInvestigationRunStore",
    "InMemoryReadInvestigationRunProgressStore",
    "InteractiveReadInvestigationConfig",
    "InteractiveReadInvestigationCoordinator",
    "InteractiveReadInvestigationSubmission",
    "HypothesisRevisionSet",
    "PlanLatencyEstimate",
    "MAX_READ_INVESTIGATION_ATTEMPTS",
    "ReadInvestigationExecutionMode",
    "READ_INVESTIGATION_INTENT_SPECS",
    "ReadInvestigationIntentSpec",
    "read_investigation_intent_spec",
    "ReadInvestigationBudget",
    "ReadInvestigationOutcome",
    "ReadInvestigationPlan",
    "ReadInvestigationProgressKind",
    "ReadInvestigationRequest",
    "ReadInvestigationModeSelector",
    "ReadInvestigationResult",
    "ReadInvestigationRunConflictError",
    "ReadInvestigationRunLease",
    "ReadInvestigationRunMode",
    "ReadInvestigationRunProgress",
    "ReadInvestigationRunProgressStore",
    "ReadInvestigationRunRecord",
    "ReadInvestigationRunState",
    "ReadInvestigationRunStore",
    "ReadInvestigationRunUsage",
    "ReadInvestigationService",
    "ReadInvestigationStep",
    "ReadLatencyProfile",
    "ReadToolSpec",
    "VerifiedObservationGateway",
    "VerifiedObservationPlanBinding",
    "build_adaptive_investigation_iteration",
    "build_adaptive_investigation_result",
    "build_adaptive_observation_execution",
    "build_hypothesis_revision_set",
    "build_verified_observation_plan_binding",
    "adaptive_result_from_mapping",
    "adaptive_result_to_mapping",
    "estimate_parallel_p95",
    "estimate_plan_latency",
    "estimate_sequential_p95",
    "latency_profile",
    "plan_read_investigation",
    "project_adaptive_investigation_room",
    "read_investigation_request_digest",
    "read_investigation_request_projection",
    "read_investigation_run_id",
    "read_tool_spec",
    "resource_name_from_question",
]
