schema_version: 1.0.0
id: azure-builtin.network.private-endpoint.configure-private-dns-zones-for-private-endpoints-that-connect-to-azure-maps-accounts
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: network.private-endpoint
check_logic:
  kind: expression
  reference: azure-policy://a58f2efa-faf4-434a-8fe9-2dca18adb5f5
remediation:
  template_ref: remediation/azure-builtin/a58f2efa-faf4-434a-8fe9-2dca18adb5f5.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: a58f2efa-faf4-434a-8fe9-2dca18adb5f5
  azure_policy_display_name: Configure private DNS zones for private endpoints that
    connect to Azure Maps Accounts.
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Maps
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Maps/AutoConfigure_PrivateDNSZone_DINE.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
