schema_version: 1.0.0
id: azure-builtin.network.private-endpoint.configure-a-private-dns-zone-id-for-queue-groupid
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: network.private-endpoint
check_logic:
  kind: expression
  reference: azure-policy://bcff79fb-2b0d-47c9-97e5-3023479b00d1
remediation:
  template_ref: remediation/azure-builtin/bcff79fb-2b0d-47c9-97e5-3023479b00d1.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: bcff79fb-2b0d-47c9-97e5-3023479b00d1
  azure_policy_display_name: Configure a private DNS Zone ID for queue groupID
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Storage
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Storage/StoragePrivateDnsZoneGroup_Queue.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
