schema_version: 1.0.0
id: azure-builtin.azure.storage.storageaccounts.blobservices.modify-configure-your-storage-account-to-enable-blob-versioning
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: azure.storage.storageaccounts.blobservices
check_logic:
  kind: expression
  reference: azure-policy://978deb5d-c9a7-41f8-b4b2-b76880d0de1f
remediation:
  template_ref: remediation/azure-builtin/978deb5d-c9a7-41f8-b4b2-b76880d0de1f.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 978deb5d-c9a7-41f8-b4b2-b76880d0de1f
  azure_policy_display_name: Modify - Configure your Storage account to enable blob
    versioning
  azure_policy_effect_default: Modify
  azure_policy_category: Storage
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Storage/StorageAccountEnableBlobVersion_Modify.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
