schema_version: 1.0.0
id: azure-builtin.object-storage.storage-accounts-should-have-shared-access-signature-sas-policies-configured
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: object-storage
check_logic:
  kind: expression
  reference: azure-policy://bc1b984e-ddae-40cc-801a-050a030e4fbe
remediation:
  template_ref: remediation/azure-builtin/bc1b984e-ddae-40cc-801a-050a030e4fbe.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: bc1b984e-ddae-40cc-801a-050a030e4fbe
  azure_policy_display_name: Storage accounts should have shared access signature
    (SAS) policies configured
  azure_policy_effect_default: Audit
  azure_policy_category: Storage
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Storage/StorageAccountSasPolicy_Restrict.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
