"""Autonomous, evidence-governed assurance for completed conversations."""

from fdai.core.conversation_assurance.attribution import (
    AdequacyCandidateKind,
    AdequacyReviewState,
    AnswerFailureAttribution,
    FailureLayer,
    HoldingOntologyAdequacyInvestigator,
    OntologyAdequacyInvestigator,
    OntologyAdequacyReview,
    OntologyAdequacyReviewSink,
    attribute_answer_failure,
    build_ontology_adequacy_review,
)
from fdai.core.conversation_assurance.consensus import MixedFamilyAssuranceReviewer
from fdai.core.conversation_assurance.deterministic import assess_deterministically
from fdai.core.conversation_assurance.identity import assurance_principal_scope
from fdai.core.conversation_assurance.learning import (
    AccuracyPosterior,
    FailureCluster,
    cluster_failures,
)
from fdai.core.conversation_assurance.ledger import (
    ConversationAssuranceLedger,
    InMemoryConversationAssuranceLedger,
)
from fdai.core.conversation_assurance.lifecycle import (
    BlindPolicyTrialMeasurer,
    ChatPolicyProposal,
    ChatPolicyProposer,
    ChatPolicyPublisher,
    ConversationAssuranceLifecycleCoordinator,
    ConversationAssuranceLifecycleRunner,
)
from fdai.core.conversation_assurance.models import (
    CRITERION_WEIGHTS,
    AssessmentRecord,
    AssessmentState,
    AssuranceCriterion,
    AssuranceDecision,
    AssuranceVerdict,
    ConversationAssuranceEvaluator,
    CriterionScore,
    DebateContext,
    DeterministicAssessment,
    DisputeReason,
    DisputeRecord,
    EvaluatorOutput,
    TurnAssessmentInput,
)
from fdai.core.conversation_assurance.pantheon_aggregation import (
    AgentDiagnosticSummary,
    PantheonDiagnosticSummary,
    aggregate_pantheon_diagnostics,
)
from fdai.core.conversation_assurance.pantheon_campaign import (
    CampaignHoldError,
    CampaignRunResult,
    CampaignState,
    PantheonCampaignController,
    PantheonCaseEvaluator,
)
from fdai.core.conversation_assurance.pantheon_census import (
    PantheonCensus,
    PantheonCensusCase,
    build_pantheon_census,
    t2_expected_outcome,
)
from fdai.core.conversation_assurance.pantheon_hardening import (
    HardeningDecision,
    HardeningDisposition,
    PantheonWeakness,
    classify_hardening,
)
from fdai.core.conversation_assurance.pantheon_ledger import (
    PrivateJsonlLedger,
    open_private_lock,
    private_marker_exists,
    read_private_text,
    remove_private_marker,
    touch_private_marker,
)
from fdai.core.conversation_assurance.pantheon_scorecard import (
    PantheonDiagnosticCase,
    PantheonDiagnosticVerdict,
    PantheonRubric,
    PantheonRubricResult,
    PantheonSemanticReview,
    PantheonTurnDiagnostic,
    T2Expectation,
    evaluate_pantheon_turn,
    required_observed_rubrics,
    semantic_rubrics,
)
from fdai.core.conversation_assurance.pantheon_trace import (
    ConversationTurnTraceReceipt,
    ParticipantPromptReceipt,
    content_digest,
)
from fdai.core.conversation_assurance.policy_store import (
    ConversationPolicyCandidateStore,
    InMemoryConversationPolicyCandidateStore,
)
from fdai.core.conversation_assurance.promotion import (
    ChatPolicyCandidate,
    ChatPolicyTarget,
    PolicyStage,
    PolicyTransition,
    PolicyTrialMetrics,
    PromotionConfig,
    evaluate_policy_transition,
)
from fdai.core.conversation_assurance.quality_context_locale_observations import (
    ContextIsolationScenarioResult,
    LocaleParityScenarioResult,
    PersistenceFidelityScenarioResult,
    PersonalizationAccuracyScenarioResult,
    ScreenAwarenessScenarioResult,
    critical_safety_escape_item_ids,
    observe_context_and_locale,
    observe_context_isolation,
    observe_locale_parity,
    observe_persistence_fidelity,
    observe_personalization_accuracy,
    observe_screen_awareness,
)
from fdai.core.conversation_assurance.quality_scorecard import (
    CHATOPS_QUALITY_CONTRACT_V1,
    ChatOpsQualityContract,
    QualityDimension,
    QualityHardCap,
    QualityItemMeasurement,
    QualityItemScore,
    QualityRubricItem,
    score_quality_item,
)
from fdai.core.conversation_assurance.runtime_policy import (
    BASE_POLICY_DIGEST,
    AppliedChatPolicy,
    ConversationPolicyRuntime,
    policy_is_assigned,
)
from fdai.core.conversation_assurance.service import (
    AssuranceReview,
    ConversationAssuranceCoordinator,
)

__all__ = [
    "CRITERION_WEIGHTS",
    "AdequacyCandidateKind",
    "AdequacyReviewState",
    "AccuracyPosterior",
    "AgentDiagnosticSummary",
    "AppliedChatPolicy",
    "BASE_POLICY_DIGEST",
    "AssessmentRecord",
    "AssessmentState",
    "AnswerFailureAttribution",
    "BlindPolicyTrialMeasurer",
    "CampaignHoldError",
    "CampaignRunResult",
    "CampaignState",
    "ContextIsolationScenarioResult",
    "AssuranceCriterion",
    "AssuranceDecision",
    "AssuranceReview",
    "AssuranceVerdict",
    "ChatPolicyProposal",
    "ChatPolicyProposer",
    "ChatPolicyPublisher",
    "ConversationAssuranceEvaluator",
    "ConversationAssuranceCoordinator",
    "ConversationAssuranceLedger",
    "ConversationAssuranceLifecycleCoordinator",
    "ConversationAssuranceLifecycleRunner",
    "ConversationTurnTraceReceipt",
    "ConversationPolicyRuntime",
    "ConversationPolicyCandidateStore",
    "CriterionScore",
    "DebateContext",
    "DeterministicAssessment",
    "DisputeReason",
    "DisputeRecord",
    "EvaluatorOutput",
    "FailureCluster",
    "FailureLayer",
    "HardeningDecision",
    "HardeningDisposition",
    "HoldingOntologyAdequacyInvestigator",
    "InMemoryConversationAssuranceLedger",
    "InMemoryConversationPolicyCandidateStore",
    "LocaleParityScenarioResult",
    "MixedFamilyAssuranceReviewer",
    "OntologyAdequacyReview",
    "OntologyAdequacyInvestigator",
    "OntologyAdequacyReviewSink",
    "PantheonCensus",
    "PantheonCensusCase",
    "PantheonCampaignController",
    "PantheonCaseEvaluator",
    "PantheonDiagnosticCase",
    "PantheonDiagnosticSummary",
    "PantheonDiagnosticVerdict",
    "PantheonRubric",
    "PantheonRubricResult",
    "PantheonSemanticReview",
    "PantheonTurnDiagnostic",
    "PantheonWeakness",
    "ParticipantPromptReceipt",
    "PersistenceFidelityScenarioResult",
    "TurnAssessmentInput",
    "T2Expectation",
    "ChatPolicyCandidate",
    "ChatPolicyTarget",
    "ChatOpsQualityContract",
    "CHATOPS_QUALITY_CONTRACT_V1",
    "PolicyStage",
    "PolicyTransition",
    "PolicyTrialMetrics",
    "PrivateJsonlLedger",
    "PersonalizationAccuracyScenarioResult",
    "PromotionConfig",
    "QualityDimension",
    "QualityHardCap",
    "QualityItemMeasurement",
    "QualityItemScore",
    "QualityRubricItem",
    "ScreenAwarenessScenarioResult",
    "assess_deterministically",
    "aggregate_pantheon_diagnostics",
    "attribute_answer_failure",
    "assurance_principal_scope",
    "cluster_failures",
    "classify_hardening",
    "build_ontology_adequacy_review",
    "build_pantheon_census",
    "t2_expected_outcome",
    "content_digest",
    "evaluate_policy_transition",
    "evaluate_pantheon_turn",
    "critical_safety_escape_item_ids",
    "observe_context_and_locale",
    "observe_context_isolation",
    "observe_locale_parity",
    "observe_persistence_fidelity",
    "observe_personalization_accuracy",
    "observe_screen_awareness",
    "open_private_lock",
    "policy_is_assigned",
    "private_marker_exists",
    "read_private_text",
    "remove_private_marker",
    "score_quality_item",
    "required_observed_rubrics",
    "semantic_rubrics",
    "touch_private_marker",
]
