schema_version: 1.0.0
id: azure-builtin.azure.machinelearningservices.workspaces.configure-azure-machine-learning-workspaces-with-private-endpoints
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: azure.machinelearningservices.workspaces
check_logic:
  kind: expression
  reference: azure-policy://7838fd83-5cbb-4b5d-888c-bfa240972597
remediation:
  template_ref: remediation/azure-builtin/7838fd83-5cbb-4b5d-888c-bfa240972597.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 7838fd83-5cbb-4b5d-888c-bfa240972597
  azure_policy_display_name: Configure Azure Machine Learning workspaces with private
    endpoints
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Machine Learning
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Machine
    Learning/Workspace_PrivateEndpoint_DINE.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
