"""Environment keys consumed by the production read API composition."""

from typing import Final

DATABASE_URL_ENV: Final[str] = "FDAI_DATABASE_URL"
CORS_ORIGINS_ENV: Final[str] = "FDAI_READ_API_CORS_ALLOW_ORIGINS"
ONBOARDING_ENV: Final[tuple[str, ...]] = (
    "AZURE_SUBSCRIPTION_ID",
    "AZURE_RESOURCE_GROUP",
    "FDAI_EXECUTOR_PRINCIPAL_ID",
    "FDAI_EXECUTOR_EVENT_ROLE_DEFINITION_ID",
    "FDAI_EXECUTOR_SECRET_ROLE_DEFINITION_ID",
)
INVENTORY_FRESHNESS_ENV: Final[str] = "FDAI_INVENTORY_FRESHNESS_SECONDS"
TENANT_ENV: Final[str] = "FDAI_ENTRA_TENANT_ID"
AUDIENCE_ENV: Final[str] = "FDAI_API_AUDIENCE"
HIL_SECRET_ENV: Final[str] = "FDAI_CHATOPS_WEBHOOK_SECRET"  # noqa: S105
HIL_TOPIC_ENV: Final[str] = "FDAI_HIL_DECISION_TOPIC"
STAGE_TOPIC_ENV: Final[str] = "FDAI_STAGE_TOPIC"
EVENT_TOPIC_ENV: Final[str] = "KAFKA_TOPIC_EVENTS"
INCIDENT_SLA_POLICY_ENV: Final[str] = "FDAI_INCIDENT_SLA_POLICY_JSON"
INCIDENT_SLA_INTERVAL_ENV: Final[str] = "FDAI_INCIDENT_SLA_INTERVAL_SECONDS"
PYTHON_TASK_AUTHOR_ENDPOINT_ENV: Final[str] = "FDAI_PYTHON_TASK_AUTHOR_ENDPOINT"
PYTHON_TASK_AUTHOR_DEPLOYMENT_ENV: Final[str] = "FDAI_PYTHON_TASK_AUTHOR_DEPLOYMENT"
RESOLVED_MODELS_ENV: Final[str] = "LLM_RESOLVED_MODELS_PATH"
IAM_DIRECTORY_PROVIDER_ENV: Final[str] = "FDAI_IAM_DIRECTORY_PROVIDER"
IAM_ENTRA_BASE_URL_ENV: Final[str] = "FDAI_IAM_ENTRA_GRAPH_BASE_URL"

__all__ = [name for name in globals() if name.isupper()]
