// Source: https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations
// CSP-neutral types without a one-to-one CAF row use an explicit, stable extension below.
export const ARCHITECTURE_RESOURCE_ABBREVIATIONS = {
  subscription: "sub",
  "resource-group": "rg",
  "virtual-network": "vnet",
  subnet: "snet",
  "front-door": "afd",
  "application-gateway": "agw",
  "web-application-firewall": "waf",
  waf: "waf",
  firewall: "afw",
  "key-vault": "kv",
  "secret-store": "kv",
  "network-security-group": "nsg",
  nsg: "nsg",
  "load-balancer": "lb",
  "l4-load-balancer": "lb",
  "app-service": "app",
  "container-app": "ca",
  "compute.container-app-job": "caj",
  "compute.container-app-environment": "cae",
  "function-app": "func",
  "app-service-plan": "asp",
  "static-web-app": "stapp",
  "aks-cluster": "aks",
  postgresql: "pgsql",
  "postgresql-server": "pgsql",
  "mysql-server": "mysql",
  "sql-database": "sqldb",
  redis: "redis",
  "storage-account": "st",
  "object-storage": "st",
  "event-hub": "evhns",
  "event-hubs": "evhns",
  "service-bus": "sbns",
  queue: "sbq",
  "message-queue": "sbq",
  kafka: "kafka",
  "compute.vm": "vm",
  "compute.vm-scale-set": "vmss",
  "compute.container-app": "ca",
  "compute.function": "func",
  "compute.web-app": "app",
  "workflow.logic-app": "logic",
  "kubernetes-cluster": "aks",
  "kubernetes-node-pool": "np",
  "llm-endpoint": "oai",
  "network.vnet": "vnet",
  "network.subnet": "snet",
  "network.nsg": "nsg",
  "network.firewall": "afw",
  "network.interface": "nic",
  "network.private-endpoint": "pep",
  "network.load-balancer": "lb",
  "network.application-gateway": "agw",
  "api-gateway": "apim",
  "network.dns-zone": "dns",
  "network.public-ip": "pip",
  "network.nat-gateway": "ng",
  "network.private-dns-zone": "pdns",
  "network.private-dns-zone-link": "pdnsl",
  "network.dns-resolver": "dnspr",
  "network.dns-resolver-inbound-endpoint": "in",
  "network.virtual-network-gateway": "vgw",
  "diagnostic-settings": "diag",
  "file-share": "share",
  disk: "disk",
  "container-registry": "cr",
  "nosql-database": "cosno",
  cache: "redis",
  "redis-enterprise": "amr",
  "managed-identity": "id",
  certificate: "cert",
  "log-workspace": "log",
  "metrics-workspace": "amw",
  "application-insights": "appi",
  "data-collection-rule": "dcr",
  "event-grid-topic": "egst",
  "communication-service": "acs",
  "email-service": "email",
  "email-domain": "domain",
} as const satisfies Readonly<Record<string, string>>;

export function hasArchitectureResourceAbbreviation(type: string): boolean {
  return Object.hasOwn(ARCHITECTURE_RESOURCE_ABBREVIATIONS, type);
}

export function architectureResourceAbbreviation(type: string): string {
  return ARCHITECTURE_RESOURCE_ABBREVIATIONS[
    type as keyof typeof ARCHITECTURE_RESOURCE_ABBREVIATIONS
  ] ?? "res";
}
