schema_version: 1.0.0
id: azure-builtin.azure.hybridcompute.privatelinkscopes.configure-azure-arc-private-link-scopes-with-private-endpoints
version: 2.0.0
source: azure_policy
severity: medium
category: security
resource_type: azure.hybridcompute.privatelinkscopes
check_logic:
  kind: expression
  reference: azure-policy://d6eeba80-df61-4de5-8772-bc1b7852ba6b
remediation:
  template_ref: remediation/azure-builtin/d6eeba80-df61-4de5-8772-bc1b7852ba6b.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: d6eeba80-df61-4de5-8772-bc1b7852ba6b
  azure_policy_display_name: Configure Azure Arc Private Link Scopes with private
    endpoints
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Azure Arc
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Arc/Arc_PrivateEndpoint_DINE.json
  source_version: 2.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
