"""Shared Bragi runtime constants."""

from __future__ import annotations

from datetime import timedelta

_BRAGI_STATE_PREFIX = "pantheon/bragi"
_INTENT_TRAINING_EVIDENCE_PREFIX = f"{_BRAGI_STATE_PREFIX}/intent-training/"
_INTENT_TRAINING_EVIDENCE_RETENTION = 1_024
_USER_PREFERENCE_INDEX_PREFIX = f"{_BRAGI_STATE_PREFIX}/user-preference-index/"
_USER_PREFERENCE_INDEX_SCAN_LIMIT = 1_000
_TURN_OUTBOX_PENDING_SCAN_LIMIT = 5_000
_TURN_OUTBOX_TOMBSTONE_RETENTION = 1_024
_TURN_OUTBOX_MAINTENANCE_PAGE = 16
_TURN_OUTBOX_CLAIM_LEASE = timedelta(minutes=5)
_MAX_SESSIONS = 1_000
_MAX_SESSION_TURNS = 100
_MAX_QUESTION_CHARS = 2_000
_MAX_ANSWER_CHARS = 16_000
_MAX_PROGRESS_KEYS = 5_000
_DURABLE_PROGRESS_RETENTION = _MAX_PROGRESS_KEYS
_MAX_PROGRESS_STEPS = 64
_MAX_CONTRIBUTORS = 2
_CONTRIBUTOR_TIMEOUT_SECONDS = 1.2
_SESSION_INACTIVITY_LIMIT = timedelta(minutes=30)

__all__ = [
    "_BRAGI_STATE_PREFIX",
    "_CONTRIBUTOR_TIMEOUT_SECONDS",
    "_DURABLE_PROGRESS_RETENTION",
    "_INTENT_TRAINING_EVIDENCE_PREFIX",
    "_INTENT_TRAINING_EVIDENCE_RETENTION",
    "_MAX_ANSWER_CHARS",
    "_MAX_CONTRIBUTORS",
    "_MAX_QUESTION_CHARS",
    "_MAX_PROGRESS_KEYS",
    "_MAX_PROGRESS_STEPS",
    "_MAX_SESSION_TURNS",
    "_MAX_SESSIONS",
    "_SESSION_INACTIVITY_LIMIT",
    "_TURN_OUTBOX_CLAIM_LEASE",
    "_TURN_OUTBOX_MAINTENANCE_PAGE",
    "_TURN_OUTBOX_PENDING_SCAN_LIMIT",
    "_TURN_OUTBOX_TOMBSTONE_RETENTION",
    "_USER_PREFERENCE_INDEX_PREFIX",
    "_USER_PREFERENCE_INDEX_SCAN_LIMIT",
]
