schema_version: 1.0.0
id: azure-builtin.azure.kusto.clusters.configure-azure-data-explorer-clusters-with-private-endpoints
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: azure.kusto.clusters
check_logic:
  kind: expression
  reference: azure-policy://a47272e1-1d5d-4b0b-b366-4873f1432fe0
remediation:
  template_ref: remediation/azure-builtin/a47272e1-1d5d-4b0b-b366-4873f1432fe0.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: a47272e1-1d5d-4b0b-b366-4873f1432fe0
  azure_policy_display_name: Configure Azure Data Explorer clusters with private endpoints
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: Azure Data Explorer
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Azure
    Data Explorer/ADX_PrivateEndpoint_DINE.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
