schema_version: 1.0.0
id: azure-builtin.compute.vm.configure-windows-vms-to-install-ama-for-changetracking-and-inventory-with-user-assigned-managed-ide
version: 1.4.0
source: azure_policy
severity: medium
category: security
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://ad1eeff9-20d7-4c82-a04e-903acab0bfc1
remediation:
  template_ref: remediation/azure-builtin/ad1eeff9-20d7-4c82-a04e-903acab0bfc1.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: ad1eeff9-20d7-4c82-a04e-903acab0bfc1
  azure_policy_display_name: Configure Windows VMs to install AMA for ChangeTracking
    and Inventory with user-assigned managed identity
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: ChangeTrackingAndInventory
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/ChangeTrackingAndInventory/AMA_UAI_Windows_VM_DINE.json
  source_version: 1.4.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
