schema_version: 1.0.0
id: azure-builtin.compute.vm-scale-set.configure-windows-vmss-to-be-associated-with-a-data-collection-rule-for-changetracking-and-in
version: 1.2.0
source: azure_policy
severity: medium
category: security
resource_type: compute.vm-scale-set
check_logic:
  kind: expression
  reference: azure-policy://8fd85785-1547-4a4a-bf90-d5483c9571c5
remediation:
  template_ref: remediation/azure-builtin/8fd85785-1547-4a4a-bf90-d5483c9571c5.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 8fd85785-1547-4a4a-bf90-d5483c9571c5
  azure_policy_display_name: Configure Windows VMSS to be associated with a Data Collection
    Rule for ChangeTracking and Inventory
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: ChangeTrackingAndInventory
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/ChangeTrackingAndInventory/DCRA_Windows_VMSS_DINE.json
  source_version: 1.2.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
