import type {
  CostGovernanceProjection,
  CostGovernanceSurface,
} from "../api-cost-governance";

const SAMPLE_AT = "2026-08-31T09:00:00Z";
const SAMPLE_WINDOW_START = "2026-08-01T00:00:00Z";
const SAMPLE_DIGEST = `sha256:${"a".repeat(64)}`;

const COST_ITEMS: CostGovernanceProjection["items"] = [
  {
    record_id: "sample-compute",
    kind: "service-cost",
    service_id: "Compute",
    amount_exact: 42800,
    currency: "USD",
    record_count: 84,
    status: "observed",
    observed_at: SAMPLE_AT,
    completeness: 1,
    relative_change: -0.08,
    source_authority: "synthetic-preview",
  },
  {
    record_id: "sample-database",
    kind: "service-cost",
    service_id: "Databases",
    amount_exact: 31600,
    currency: "USD",
    record_count: 42,
    status: "observed",
    observed_at: SAMPLE_AT,
    completeness: 1,
    relative_change: 0.04,
    source_authority: "synthetic-preview",
  },
  {
    record_id: "sample-observability",
    kind: "service-cost",
    service_id: "Observability",
    amount_exact: 18400,
    currency: "USD",
    record_count: 36,
    status: "observed",
    observed_at: SAMPLE_AT,
    completeness: 1,
    relative_change: -0.03,
    source_authority: "synthetic-preview",
  },
  {
    record_id: "sample-ai",
    kind: "service-cost",
    service_id: "AI services",
    amount_exact: 12700,
    currency: "USD",
    record_count: 28,
    status: "observed",
    observed_at: SAMPLE_AT,
    completeness: 1,
    relative_change: 0.06,
    source_authority: "synthetic-preview",
  },
];

const RESOURCE_CANDIDATE_ITEMS: CostGovernanceProjection["items"] = [
  {
    kind: "resource_candidate",
    recommendation_ref: "recommendation:1111111111111111",
    resource: "resource:111111111111111111111111",
    resource_type: "compute.virtual-machine",
    current_configuration: "sample-large",
    proposed_configuration: "sample-medium",
    utilization_metric: "cpu.hourly_average.p95",
    utilization_percent: 18,
    projected_monthly_savings: 18400,
    currency: "USD",
    observed_at: SAMPLE_AT,
    source_authority: "synthetic-preview",
  },
  {
    kind: "resource_candidate",
    recommendation_ref: "recommendation:2222222222222222",
    resource: "resource:222222222222222222222222",
    resource_type: "data.postgresql",
    current_configuration: "sample-memory-optimized",
    proposed_configuration: "sample-general-purpose",
    utilization_metric: "capacity.hourly_average.p95",
    utilization_percent: 42,
    projected_monthly_savings: 49800,
    currency: "USD",
    observed_at: SAMPLE_AT,
    source_authority: "synthetic-preview",
  },
];

const OPTIMIZATION_CASE_ITEMS: CostGovernanceProjection["items"] = [
  {
    kind: "decision_case",
    case_ref: "case:111111111111111111111111",
    revision: 1,
    target_refs: ["resource:111111111111111111111111"],
    evidence_cutoff: SAMPLE_AT,
    decision_frame_digest: SAMPLE_DIGEST,
    option_ids: ["option.no-action", "option.review-smaller-sku"],
    selected_option_id: "option.no-action",
    verdict: "hold",
    reason: "sample_observation_mode",
    evidence_refs: ["sample:cost", "sample:capacity"],
    evidence_sources: ["synthetic-preview"],
    recovery_steps: [],
    recorded_at: SAMPLE_AT,
    source_authority: "synthetic-preview",
  },
  {
    kind: "decision_case",
    case_ref: "case:222222222222222222222222",
    revision: 1,
    target_refs: ["resource:222222222222222222222222"],
    evidence_cutoff: SAMPLE_AT,
    decision_frame_digest: SAMPLE_DIGEST,
    option_ids: ["option.no-action", "option.review-general-purpose"],
    selected_option_id: "option.no-action",
    verdict: "hold",
    reason: "sample_observation_mode",
    evidence_refs: ["sample:cost", "sample:capacity"],
    evidence_sources: ["synthetic-preview"],
    recovery_steps: [],
    recorded_at: SAMPLE_AT,
    source_authority: "synthetic-preview",
  },
];

const OUTCOME_ITEMS: CostGovernanceProjection["items"] = [
  {
    kind: "settlement_outcome",
    case_ref: "case:111111111111111111111111",
    revision: 2,
    action_ref: "action:111111111111111111111111",
    action_revision: 1,
    decision_frame_digest: SAMPLE_DIGEST,
    terminal: true,
    verified_savings: 12800,
    currency: "USD",
    rollback_requested: false,
    recovery_observed: false,
    effects: [
      {
        effect_id: "sample-cost-effect",
        kind: "cost",
        status: "verified",
        reason: "sample_effect_observed",
        terminal: true,
        observation_digest: SAMPLE_DIGEST,
        completeness_digest: SAMPLE_DIGEST,
      },
      {
        effect_id: "sample-service-effect",
        kind: "service",
        status: "verified",
        reason: "sample_effect_observed",
        terminal: true,
        observation_digest: SAMPLE_DIGEST,
        completeness_digest: SAMPLE_DIGEST,
      },
    ],
    settled_at: SAMPLE_AT,
  },
  {
    kind: "settlement_outcome",
    case_ref: "case:222222222222222222222222",
    revision: 2,
    action_ref: "action:222222222222222222222222",
    action_revision: 1,
    decision_frame_digest: SAMPLE_DIGEST,
    terminal: true,
    verified_savings: 28600,
    currency: "USD",
    rollback_requested: false,
    recovery_observed: false,
    effects: [
      {
        effect_id: "sample-cost-effect",
        kind: "cost",
        status: "verified",
        reason: "sample_effect_observed",
        terminal: true,
        observation_digest: SAMPLE_DIGEST,
        completeness_digest: SAMPLE_DIGEST,
      },
      {
        effect_id: "sample-service-effect",
        kind: "service",
        status: "verified",
        reason: "sample_effect_observed",
        terminal: true,
        observation_digest: SAMPLE_DIGEST,
        completeness_digest: SAMPLE_DIGEST,
      },
    ],
    settled_at: SAMPLE_AT,
  },
];

function sampleItems(
  surface: CostGovernanceSurface,
): CostGovernanceProjection["items"] {
  if (surface === "resource-efficiency") return RESOURCE_CANDIDATE_ITEMS;
  if (surface === "optimization-cases") return OPTIMIZATION_CASE_ITEMS;
  if (surface === "outcomes") return OUTCOME_ITEMS;
  return COST_ITEMS;
}

export function sampleCostGovernance(
  surface: CostGovernanceSurface,
): CostGovernanceProjection {
  return {
    surface,
    complete: true,
    source_authority: "synthetic-preview",
    items: sampleItems(surface),
    suppressed_count: 0,
    generated_at: SAMPLE_AT,
    disclosure: {
      granularity: surface === "overview" ? "group" : "resource",
      identity_visibility: surface === "overview" ? "none" : "pseudonymous",
      amount_precision: "exact",
      small_cell_minimum: 3,
      rounding_increment: 100,
    },
    resource_efficiency_mode: surface === "resource-efficiency"
      ? "resource_candidate"
      : null,
    evidence: {
      window_start_at: SAMPLE_WINDOW_START,
      window_end_at: SAMPLE_AT,
      latest_source_at: SAMPLE_AT,
      freshness: "fresh",
      freshness_threshold_seconds: 172800,
      complete_count: 4,
      partial_count: 0,
      sources: [{
        source_authority: "synthetic-preview",
        state: "complete",
        window_start_at: SAMPLE_WINDOW_START,
        window_end_at: SAMPLE_AT,
        latest_source_at: SAMPLE_AT,
        complete_count: 4,
        partial_count: 0,
        reason: null,
      }],
      disclosure: {
        granularity: surface === "overview" ? "group" : "resource",
        identity_visibility: surface === "overview" ? "none" : "pseudonymous",
        amount_precision: "exact",
        small_cell_minimum: 3,
        rounding_increment: 100,
      },
      readiness: [
        { surface: "observations", state: "complete", reason: null, record_count: 190, latest_evidence_at: SAMPLE_AT },
        { surface: "analytics", state: "complete", reason: null, record_count: 1, latest_evidence_at: SAMPLE_AT },
        { surface: "resource-candidates", state: "complete", reason: null, record_count: 2, latest_evidence_at: SAMPLE_AT },
        { surface: "decision-cases", state: "complete", reason: null, record_count: 2, latest_evidence_at: SAMPLE_AT },
        { surface: "settlements", state: "complete", reason: null, record_count: 2, latest_evidence_at: SAMPLE_AT },
      ],
      latest_analytics_run: null,
    },
    analytics: {
      source_authority: "synthetic-preview",
      observed_at: SAMPLE_AT,
      complete: true,
      window_start_at: SAMPLE_WINDOW_START,
      window_end_at: SAMPLE_AT,
      sources: [],
      trend: [
        { observed_on: "2026-08-25", amount: 118400, currency: "USD", completeness: 1 },
        { observed_on: "2026-08-26", amount: 116900, currency: "USD", completeness: 1 },
        { observed_on: "2026-08-27", amount: 114800, currency: "USD", completeness: 1 },
        { observed_on: "2026-08-28", amount: 112600, currency: "USD", completeness: 1 },
        { observed_on: "2026-08-29", amount: 108900, currency: "USD", completeness: 1 },
        { observed_on: "2026-08-30", amount: 106700, currency: "USD", completeness: 1 },
        { observed_on: "2026-08-31", amount: 105500, currency: "USD", completeness: 1 },
      ],
      budgets: [
        {
          budget_ref: "sample-budget-primary",
          amount: 140000,
          current_spend: 105500,
          forecast_spend: 128400,
          currency: "USD",
          time_grain: "Monthly",
        },
      ],
      recommendations: [
        {
          recommendation_ref: "sample-rec-compute",
          resource_ref: null,
          resource_type: "compute.virtual-machine",
          problem: "Underused compute capacity",
          solution: "Review a smaller SKU",
          impact: "Medium",
          monthly_savings: 18400,
          currency: "USD",
          current_sku: "sample-large",
          target_sku: "sample-medium",
          utilization_percent: 18,
          utilization_metric: "cpu",
          observed_at: SAMPLE_AT,
          source_authority: "synthetic-preview",
        },
        {
          recommendation_ref: "sample-rec-database",
          resource_ref: null,
          resource_type: "data.postgresql",
          problem: "Excess reserved capacity",
          solution: "Review the reserved capacity envelope",
          impact: "High",
          monthly_savings: 49800,
          currency: "USD",
          current_sku: "sample-memory-optimized",
          target_sku: "sample-general-purpose",
          utilization_percent: 42,
          utilization_metric: "capacity",
          observed_at: SAMPLE_AT,
          source_authority: "synthetic-preview",
        },
      ],
      limitations: ["synthetic_preview_not_operational_evidence"],
    },
  };
}
