const SAMPLE_AT = "2026-09-01T09:00:00Z";

function publicationCounts(published = 0) {
  return {
    published,
    published_receipt_unrecorded: 0,
    duplicate_suppressed: 0,
    reconciled_duplicate: 0,
    publish_uncertain: 0,
    awaiting_reconciliation: 0,
    failed: 0,
  };
}

export function sampleOnboarding() {
  return {
    probe_mode: "configured",
    ready: false,
    blocked: true,
    missing_resources: ["state_store", "event_bus", "executor_identity"],
    missing_role_assignments: [
      ["executor", "event_bus_data_owner", "event_bus"],
      ["executor", "secret_reader", "secret_store"],
    ],
    present_resource_count: 5,
    present_role_count: 0,
    error: null,
  };
}

export function sampleDetectionReadiness() {
  return {
    source: "synthetic-preview",
    observed_at: SAMPLE_AT,
    target_count: 1,
    counts: { ready: 1, partial: 0, blocked: 0, stale: 0, unauthorized: 0, unknown: 0 },
    targets: [
      {
        resource_ref: "example-kubernetes-cluster",
        generated_at: SAMPLE_AT,
        decision: "ready",
        authority_ceiling: "shadow",
        observations: [
          { dimension: "discovered", status: "passed" },
          { dimension: "collector_configured", status: "passed" },
          { dimension: "telemetry_observed", status: "passed" },
          { dimension: "detector_bound", status: "passed" },
          { dimension: "pipeline_observed", status: "passed" },
          { dimension: "action_governed", status: "passed" },
        ],
        missing_dimensions: [],
        stale_dimensions: [],
      },
    ],
    analyzer_coverage: {
      schema_version: "1.1.0",
      status: "available",
      unavailable_reason: null,
      source: "synthetic-preview:analyzer-tick-receipt",
      recorded_at: SAMPLE_AT,
      run_attempt_id: "sample-analyzer-attempt",
      candidate_count: 7,
      selected_count: 5,
      evaluated_count: 4,
      held_count: 2,
      finding_count: 1,
      unsupported_count: 0,
      error_count: 1,
      unattributed_error_count: 0,
      unattributed_error_codes: [],
      publication_counts: publicationCounts(1),
      resource_types: [
        {
          resource_type: "api-gateway",
          candidate_count: 1,
          selected_count: 1,
          evaluated_count: 1,
          held_count: 0,
          held_reason_counts: {},
          finding_count: 0,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(),
        },
        {
          resource_type: "kubernetes-cluster",
          candidate_count: 2,
          selected_count: 1,
          evaluated_count: 1,
          held_count: 1,
          held_reason_counts: { unverified_state_fact: 1 },
          finding_count: 1,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(1),
        },
        {
          resource_type: "llm-endpoint",
          candidate_count: 1,
          selected_count: 1,
          evaluated_count: 1,
          held_count: 0,
          held_reason_counts: {},
          finding_count: 0,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(),
        },
        {
          resource_type: "mysql-server",
          candidate_count: 2,
          selected_count: 1,
          evaluated_count: 0,
          held_count: 1,
          held_reason_counts: { stale_state_fact: 1 },
          finding_count: 0,
          unsupported_count: 0,
          error_count: 1,
          error_codes: ["analyzer_timeout"],
          publication_counts: publicationCounts(),
        },
        {
          resource_type: "network.application-gateway",
          candidate_count: 1,
          selected_count: 1,
          evaluated_count: 1,
          held_count: 0,
          held_reason_counts: {},
          finding_count: 0,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(),
        },
      ],
      resources: [
        {
          resource_ref: "example-api-gateway",
          resource_type: "api-gateway",
          resource_kind: "api_management",
          evaluation_state: "evaluated_no_finding",
          finding_count: 0,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(),
        },
        {
          resource_ref: "example-kubernetes-cluster",
          resource_type: "kubernetes-cluster",
          resource_kind: "aks_cluster",
          evaluation_state: "finding",
          finding_count: 1,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(1),
        },
        {
          resource_ref: "example-llm-endpoint",
          resource_type: "llm-endpoint",
          resource_kind: "azure_openai",
          evaluation_state: "evaluated_no_finding",
          finding_count: 0,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(),
        },
        {
          resource_ref: "example-mysql-server",
          resource_type: "mysql-server",
          resource_kind: "mysql_flexible_server",
          evaluation_state: "evaluation_error",
          finding_count: 0,
          unsupported_count: 0,
          error_count: 1,
          error_codes: ["analyzer_timeout"],
          publication_counts: publicationCounts(),
        },
        {
          resource_ref: "example-application-gateway",
          resource_type: "network.application-gateway",
          resource_kind: "application_gateway",
          evaluation_state: "evaluated_no_finding",
          finding_count: 0,
          unsupported_count: 0,
          error_count: 0,
          error_codes: [],
          publication_counts: publicationCounts(),
        },
      ],
      cause_claim_supported: false,
      execution_authority: false,
    },
    analyzer_run: {
      source: "synthetic-preview:analyzer-tick-receipt",
      recorded_at: SAMPLE_AT,
      targets: 5,
      findings: 1,
      published: 1,
      duplicates_suppressed: 0,
      uncertain: 0,
      configured_targets: 0,
      discovered_targets: 5,
      candidate_count: 7,
      inventory_consulted: true,
      source_complete: true,
      truncated: false,
      skipped_reasons: ["unverified_state_fact"],
      skipped_reason_counts: { unverified_state_fact: 2 },
      unsupported_target_count: 0,
      analyzer_error_count: 0,
      publish_error_count: 0,
      receipt_error_count: 0,
      scheduling: "local_loop",
      metric_access: "available",
      event_publication: "verified",
      execution_authority: false,
    },
    lifecycle: {
      source: "synthetic-preview",
      observed_at: SAMPLE_AT,
      retained_from: "2026-09-01T08:57:03Z",
      receipt_count: 3,
      receipt_limit: 500,
      target_count: 2,
      assessment_count: 3,
      evidence_counts: { complete: 1, incomplete: 1, conflicting: 1, missed: 0 },
      targets: [
        {
          resource_ref: "example-workload-api",
          current: {
            idempotency_key: "analyzer:example-workload-api:container_restart:2",
            resource_ref: "example-workload-api",
            resource_kind: "kubernetes_pod",
            signal: "container_restart",
            occurred_at: "2026-09-01T08:59:58Z",
            recorded_at: SAMPLE_AT,
            current_state: "running",
            detection_latency_seconds: 2,
            evidence_complete: true,
            evidence_state: "complete",
            publication: {
              current: "duplicate_suppressed",
              attempts: ["published", "duplicate_suppressed"],
              duplicate_observed: true,
            },
            recovery_state: "verified",
            evidence_refs: ["example-evidence-lifecycle-1"],
            cause_claim_supported: false,
            execution_authority: false,
          },
          history: [
            {
              idempotency_key: "analyzer:example-workload-api:container_restart:1",
              resource_ref: "example-workload-api",
              resource_kind: "kubernetes_pod",
              signal: "container_restart",
              occurred_at: "2026-09-01T08:57:00Z",
              recorded_at: "2026-09-01T08:57:03Z",
              current_state: "failed",
              detection_latency_seconds: 3,
              evidence_complete: false,
              evidence_state: "incomplete",
              publication: {
                current: "awaiting_reconciliation",
                attempts: ["awaiting_reconciliation"],
                duplicate_observed: false,
              },
              recovery_state: "open",
              evidence_refs: ["example-evidence-lifecycle-0"],
              cause_claim_supported: false,
              execution_authority: false,
            },
          ],
        },
        {
          resource_ref: "example-workload-worker",
          current: {
            idempotency_key: "analyzer:example-workload-worker:conflicting_evidence:1",
            resource_ref: "example-workload-worker",
            resource_kind: "kubernetes_pod",
            signal: "conflicting_evidence",
            occurred_at: "2026-09-01T08:59:56Z",
            recorded_at: SAMPLE_AT,
            current_state: "unknown",
            detection_latency_seconds: 4,
            evidence_complete: false,
            evidence_state: "conflicting",
            publication: {
              current: "publish_uncertain",
              attempts: ["publish_uncertain"],
              duplicate_observed: false,
            },
            recovery_state: "unknown",
            evidence_refs: [
              "example-evidence-worker-a",
              "example-evidence-worker-b",
            ],
            cause_claim_supported: false,
            execution_authority: false,
          },
          history: [],
        },
      ],
    },
    pod_lifecycle: {
      schema_version: 1,
      status: "available",
      unavailable_reason: null,
      target_count: 2,
      failure_total: 1,
      gap_target_count: 1,
      counts: { recovered: 1, failing: 0, unknown: 1 },
      recovery_counts: { verified: 1, not_verified: 0, unknown: 1 },
      cause_claim_supported: false,
      execution_authority: false,
      targets: [
        {
          resource_ref: "example-workload-api",
          generated_at: SAMPLE_AT,
          stale: false,
          projection_age_seconds: 0,
          current_state: "recovered",
          current_signal: "container_restart",
          current_state_observed_at: SAMPLE_AT,
          recovery_state: "verified",
          recovery_verified_at: SAMPLE_AT,
          failure_count: 1,
          failures: [
            {
              idempotency_key: "analyzer:example-workload-api:container_restart:1",
              signal: "container_restart",
              occurred_at: "2026-09-01T08:57:00Z",
              recorded_at: "2026-09-01T08:57:03Z",
              detection_latency_seconds: 3,
              evidence_complete: true,
              recovery_closed: true,
              recovery_status: "restart_observed_recovered",
              publication: "published",
              evidence_refs: ["example-evidence-lifecycle-0"],
              evidence_gaps: [],
            },
          ],
          retained_record_count: 2,
          evidence_gaps: [],
          evidence_gap_details: [],
          delivery_counts: {
            published: 1,
            published_receipt_unrecorded: 0,
            duplicate_suppressed: 0,
            reconciled_duplicate: 0,
            publish_uncertain: 0,
            awaiting_reconciliation: 0,
            failed: 0,
          },
        },
        {
          resource_ref: "example-workload-worker",
          generated_at: SAMPLE_AT,
          stale: false,
          projection_age_seconds: 0,
          current_state: "unknown",
          current_signal: "conflicting_evidence",
          current_state_observed_at: null,
          recovery_state: "unknown",
          recovery_verified_at: null,
          failure_count: 0,
          failures: [],
          retained_record_count: 1,
          evidence_gaps: ["conflicting_evidence", "delivery_uncertain"],
          evidence_gap_details: [
            "example-evidence-worker-a and example-evidence-worker-b disagree on the current Pod identity.",
          ],
          delivery_counts: {
            published: 0,
            published_receipt_unrecorded: 0,
            duplicate_suppressed: 0,
            reconciled_duplicate: 0,
            publish_uncertain: 1,
            awaiting_reconciliation: 0,
            failed: 0,
          },
        },
      ],
    },
  };
}

export function sampleConfigurationBaselines() {
  return {
    baseline: {
      version: "sample-v3",
      scope: "sample-scope",
      created_at: SAMPLE_AT,
      document_name: "sample-baseline.yaml",
      lifecycle: "active-pinned",
      resource_count: 18,
      topology_count: 27,
      unknown_count: 2,
    },
    versions: [
      {
        version: "sample-v3",
        status: "active",
        created_at: SAMPLE_AT,
        resource_count: 18,
        topology_count: 27,
        unknown_count: 2,
        comparison: {
          baseline_version: "sample-v2",
          verdict: "attention",
          finding_count: 2,
        },
      },
    ],
    drift: { verdict: "attention", observed_at: SAMPLE_AT, finding_count: 2 },
    knowledge: {
      status: "cited",
      citation_count: 2,
      citations: ["sample-knowledge-1", "sample-knowledge-2"],
    },
    safety: {
      mutation_count: 0,
      approval_request_count: 0,
      mitigation_execution_count: 0,
      unsupported_claim_count: 0,
    },
    performance: { total_ms: 84, observation_ms: 62, knowledge_ms: 12 },
    review: {
      configured: true,
      state: "collecting",
      completed_runs: 2,
      required_runs: 3,
      failed_attempts: 0,
    },
  };
}
