import { getLocale } from "../i18n";

const EN = {
  currentOwnershipUnavailableTitle: "Joined ownership projection unavailable",
  currentOwnershipUnavailable: "This deployment returned only the legacy declaration. Identity, scope, and assignment evidence cannot be claimed.",
  legacyOwnershipTitle: "Legacy ownership declaration",
  deploymentReadiness: "Deployment readiness",
  directorySource: "Identity source",
  assignmentSource: "Pending-change source",
  observedAt: "Observed at",
  sourceRevision: "Source revision",
  readyAgents: "Ready agents",
  coverageGapAgents: "Agents needing review",
  pendingProposals: "Pending changes",
  "readiness.ready": "Ready",
  "readiness.bindings_required": "Identity bindings required",
  "readiness.migration_required": "Schema migration required",
  "readiness.review_required": "Review required",
  "readiness.identity_unavailable": "Identity source unavailable",
  "readinessHint.ready": "Every non-autonomous agent has verified primary and backup or escalation ownership.",
  "readinessHint.bindings_required": "Replace deployment placeholders with exact identity-provider subjects before relying on this map.",
  "readinessHint.migration_required": "Migrate the deployment to ownership schema version 2 and declare duties explicitly.",
  "readinessHint.review_required": "One or more identities or coverage requirements need review.",
  "readinessHint.identity_unavailable": "The declared map remains visible, but current identity status could not be verified.",
  "directoryAvailability.available": "Available",
  "directoryAvailability.unavailable": "Unavailable",
  "directoryAvailability.unknown": "Not yet observed",
  "directoryAvailability.not_configured": "Not configured",
  "assignmentAvailability.available": "Available",
  "assignmentAvailability.truncated": "Available, partial result",
  "assignmentAvailability.unavailable": "Unavailable",
  "assignmentAvailability.restricted_or_not_configured": "Restricted or not configured",
  filtersLabel: "Current ownership filters",
  searchOwners: "Search agent, person, username, identity, or scope",
  statusFilter: "Ownership status",
  "statusFilterValue.all": "All statuses",
  "statusFilterValue.ready": "Ready",
  "statusFilterValue.attention": "Needs attention",
  "statusFilterValue.autonomous": "Autonomous",
  "statusFilterValue.proposal": "Pending change",
  filteredAgents: "{count} agents",
  noOwnersMatch: "No current ownership records match these filters.",
  primaryOwner: "Primary owner",
  backupOwners: "Backup and escalation",
  scopeAndChanges: "Scope and pending changes",
  primaryMissing: "Primary owner missing",
  backupMissing: "Backup or escalation owner missing",
  agentDomainScope: "Agent domain (not scope-bound)",
  effectiveDatesNotRecorded: "Effective dates not recorded in the current declaration",
  proposedChanges: "{count} pending changes",
  proposalState: "{state}, revision {revision}",
  technicalIdentity: "Technical identity",
  coverageCounts: "Primary {primary} / backup {backup}",
  "agentStatus.ready": "Ready",
  "agentStatus.autonomous": "Autonomous",
  "agentStatus.bindings_required": "Bindings required",
  "agentStatus.migration_required": "Migration required",
  "agentStatus.coverage_gap": "Coverage gap",
  "agentStatus.identity_unavailable": "Identity unavailable",
  "agentStatus.identity_review": "Identity review",
  "subjectResolution.resolved": "Resolved identity",
  "subjectResolution.inactive": "Inactive identity",
  "subjectResolution.placeholder": "Deployment placeholder",
  "subjectResolution.not_configured": "Identity source not configured",
  "subjectResolution.unavailable": "Identity lookup unavailable",
  "subjectResolution.not_found": "Identity not found",
  "subjectResolution.kind_mismatch": "Identity type mismatch",
  "agentLayer.sensing": "Sensing",
  "agentLayer.judge": "Decision",
  "agentLayer.executor": "Execution",
  "agentLayer.approver": "Approval",
  "agentLayer.conversational": "Narration",
  "agentLayer.auditor": "Audit",
  "agentLayer.governance": "Governance",
  "agentLayer.domain": "Domain",
} as const;

const KO: Record<keyof typeof EN, string> = {
  currentOwnershipUnavailableTitle: "통합 담당 체계 변환 결과를 사용할 수 없음",
  currentOwnershipUnavailable: "이 배포는 이전 형식의 선언만 반환했습니다. ID, 적용 범위 및 할당 근거를 확인된 정보로 표시할 수 없습니다.",
  legacyOwnershipTitle: "이전 형식의 담당 체계 선언",
  deploymentReadiness: "배포 준비 상태",
  directorySource: "ID 원본",
  assignmentSource: "변경 대기 원본",
  observedAt: "관찰 시각",
  sourceRevision: "원본 개정 번호",
  readyAgents: "준비된 에이전트",
  coverageGapAgents: "검토가 필요한 에이전트",
  pendingProposals: "변경 대기",
  "readiness.ready": "준비됨",
  "readiness.bindings_required": "ID 연결 필요",
  "readiness.migration_required": "스키마 이행 필요",
  "readiness.review_required": "검토 필요",
  "readiness.identity_unavailable": "ID 원본을 사용할 수 없음",
  "readinessHint.ready": "자율 운영하지 않는 모든 에이전트에 확인된 주 담당과 백업 또는 에스컬레이션 담당자가 있습니다.",
  "readinessHint.bindings_required": "이 담당 체계를 신뢰하기 전에 배포 자리표시자를 정확한 ID 공급자 주체로 교체하세요.",
  "readinessHint.migration_required": "배포를 담당 체계 스키마 버전 2로 이행하고 담당 유형을 명시하세요.",
  "readinessHint.review_required": "하나 이상의 ID 또는 담당 범위 요구 사항을 검토해야 합니다.",
  "readinessHint.identity_unavailable": "선언된 담당 체계는 표시되지만 현재 ID 상태를 확인할 수 없습니다.",
  "directoryAvailability.available": "사용 가능",
  "directoryAvailability.unavailable": "사용할 수 없음",
  "directoryAvailability.unknown": "아직 관찰되지 않음",
  "directoryAvailability.not_configured": "구성되지 않음",
  "assignmentAvailability.available": "사용 가능",
  "assignmentAvailability.truncated": "사용 가능, 일부 결과",
  "assignmentAvailability.unavailable": "사용할 수 없음",
  "assignmentAvailability.restricted_or_not_configured": "접근 제한 또는 구성되지 않음",
  filtersLabel: "현재 담당자 필터",
  searchOwners: "에이전트, 사람, 사용자 이름, ID 또는 범위 검색",
  statusFilter: "담당 상태",
  "statusFilterValue.all": "모든 상태",
  "statusFilterValue.ready": "준비됨",
  "statusFilterValue.attention": "확인 필요",
  "statusFilterValue.autonomous": "자율 운영",
  "statusFilterValue.proposal": "변경 대기",
  filteredAgents: "에이전트 {count}개",
  noOwnersMatch: "필터와 일치하는 현재 담당 체계가 없습니다.",
  primaryOwner: "주 담당",
  backupOwners: "백업 및 에스컬레이션",
  scopeAndChanges: "적용 범위 및 변경 대기",
  primaryMissing: "주 담당자 없음",
  backupMissing: "백업 또는 에스컬레이션 담당자 없음",
  agentDomainScope: "에이전트 영역(범위 미지정)",
  effectiveDatesNotRecorded: "현재 선언에 유효 기간이 기록되지 않음",
  proposedChanges: "변경 대기 {count}건",
  proposalState: "{state}, 개정 {revision}",
  technicalIdentity: "기술 ID",
  coverageCounts: "주 담당 {primary} / 백업 {backup}",
  "agentStatus.ready": "준비됨",
  "agentStatus.autonomous": "자율 운영",
  "agentStatus.bindings_required": "ID 연결 필요",
  "agentStatus.migration_required": "이행 필요",
  "agentStatus.coverage_gap": "담당 공백",
  "agentStatus.identity_unavailable": "ID 확인 불가",
  "agentStatus.identity_review": "ID 검토 필요",
  "subjectResolution.resolved": "확인된 ID",
  "subjectResolution.inactive": "비활성 ID",
  "subjectResolution.placeholder": "배포 자리표시자",
  "subjectResolution.not_configured": "ID 원본이 구성되지 않음",
  "subjectResolution.unavailable": "ID 조회를 사용할 수 없음",
  "subjectResolution.not_found": "ID를 찾을 수 없음",
  "subjectResolution.kind_mismatch": "ID 유형 불일치",
  "agentLayer.sensing": "감지",
  "agentLayer.judge": "판정",
  "agentLayer.executor": "실행",
  "agentLayer.approver": "승인",
  "agentLayer.conversational": "설명",
  "agentLayer.auditor": "감사",
  "agentLayer.governance": "거버넌스",
  "agentLayer.domain": "전문 영역",
};

export type OwnershipCopyKey = keyof typeof EN;

export function ownershipText(
  key: OwnershipCopyKey,
  params?: Readonly<Record<string, string | number>>,
): string {
  const template = (getLocale() === "ko" ? KO : EN)[key];
  if (params === undefined) return template;
  return template.replace(/\{(\w+)\}/g, (whole, name: string) =>
    name in params ? String(params[name]) : whole);
}
