/** Route-local English source and complete Korean overlay; machine records remain unchanged. */
import { getLocale } from "../i18n";

const EN = {
  title: "Scoped ownership",
  subtitle: "Propose duties for exact agents, scopes and effective times, separately from personal assignments.",
  boundary: "Ownership only. This editor grants no IAM role, group membership, global-map change or execution permission.",
  ownerOnly: "A server-confirmed Owner capability is required to read or propose scoped ownership.",
  catalog: "Allowed scope catalog",
  refreshCatalog: "Refresh catalog",
  sourceRevision: "Complete source revision",
  observedAt: "Observed at (UTC)",
  expiresAt: "Expires at (UTC)",
  expired: "This observation is no longer current. Refresh its source before continuing.",
  deliveryAvailable: "Review-artifact delivery is available. Availability does not mean approval or merge.",
  deliveryUnavailable: "Review-artifact delivery is unavailable. Drafts and reviews grant no ownership effect.",
  useCatalog: "Use this catalog revision for the draft",
  sourceChanged: "The draft pins a different catalog revision. Adopting this revision changes the draft and its retry identity.",
  createTitle: "Draft scoped duties",
  createHint: "Add 1-30 declarations. Core resolves current people and checks coverage; declarations are not evidence of coverage.",
  binding: "Declaration {number}",
  addBinding: "Add declaration",
  removeBinding: "Remove declaration {number}",
  agent: "Agent",
  scope: "Exact scope",
  chooseScope: "Choose a server-provided scope",
  scopeUnlisted: "Not in the current catalog",
  kind: "Subject kind",
  "kind.user": "User",
  "kind.group": "Group",
  "kind.schedule": "Configured schedule",
  subjectRef: "Exact normalized subject reference",
  subjectHint: "Use a lowercase directory object ID for a user or group, or an exact configured rotation reference. No names or search queries.",
  duty: "Duty",
  "duty.primary": "Primary",
  "duty.backup": "Backup",
  "duty.escalation": "Escalation",
  effectiveFrom: "Effective from (UTC)",
  effectiveUntil: "Effective until (UTC, exclusive)",
  timeHint: "Enter an explicit UTC timestamp: YYYY-MM-DDTHH:mm:ssZ. Today's observation cannot prove future coverage.",
  fallback: "Static fallback user reference",
  fallbackHint: "Every schedule needs a distinct static user fallback. The server resolves that person independently; a fallback is not a second duty.",
  supersedes: "Superseded Core case UUID (optional)",
  supersedesHint: "Replace one reviewed predecessor over identical agent/scopes. Use its exact Core UUID, not its Operator request ID. Approved history is not edited.",
  justification: "Justification (20-2000 characters)",
  noSecrets: "Do not enter credentials or secrets. Drafts and retry payloads stay only in memory; reloading discards unsent input.",
  create: "Request draft",
  retryCreate: "Retry unchanged creation",
  validation: "Corrections needed",
  bindingIssue: "Declaration {number}: {message}",
  createUncertain: "The request may have reached the server. Retry unchanged to recover its case ID. Editing starts a different request.",
  accepted: "Request accepted, awaiting Core. No transition or ownership effect is confirmed. Open the exact case and refresh manually.",
  busy: "Sending ownership-only request",
  caseTitle: "Open an exact scoped case",
  caseHint: "There is no case list or automatic polling. Keep the case link for manual refresh and recovery after reload.",
  caseId: "Operator case ID",
  openCase: "Open case",
  refreshCase: "Refresh case",
  caseEmpty: "Enter an exact operator- case ID to read its authoritative state.",
  caseLink: "Link to this exact case",
  invalidCaseId: "Enter operator- followed by exactly 32 lowercase hexadecimal characters.",
  revision: "Core revision",
  coreCaseId: "Core case UUID",
  requester: "Requester reference",
  state: "Authoritative case state",
  "state.awaiting_core": "Awaiting Core",
  "state.draft": "Draft",
  "state.pending_review": "Pending independent review",
  "state.approved": "Two reviews recorded",
  "state.ownership_pr_open": "Ownership review PR open",
  "state.ownership_merged": "Ownership merge recorded",
  "state.rejected": "Rejected",
  awaitingCase: "Core has not materialized this request. No revision or follow-up command is available.",
  retainedEvidence: "Retained request and plan evidence",
  planAt: "Plan checked at (UTC)",
  planDigest: "Exact retained plan digest",
  planObserved: "Coverage was reported at the plan's check time, not for the full effective interval.",
  planHeld: "The retained plan reports incomplete current coverage. Core must check current sources before submission.",
  planHistoric: "A case refresh does not renew the retained plan's timestamps. The server rechecks sources when processing each command.",
  reviews: "Recorded independent reviews: {count} / 2",
  reviewsHint: "Two distinct current Owners are required. The server rechecks every reviewer, requester, target, fallback and predecessor. Recorded reviews alone are not current authority.",
  noReviews: "No independent review recorded.",
  "decision.approve": "Approve",
  "decision.reject": "Reject",
  submit: "Submit for current-source review",
  approve: "Approve ownership plan",
  reject: "Reject ownership plan",
  retryCommand: "Retry the same command",
  commandPending: "The command's outcome is not yet confirmed. Its original revision, decision and digest are retained. Refresh manually; an unchanged revision does not confirm completion.",
  pr: "Review artifact reference",
  candidateDigest: "Artifact digest",
  merge: "Independently recorded merge commit",
  notRecorded: "Not recorded",
  observationTitle: "Read an exact scope observation",
  readObservation: "Read current observation",
  observationEmpty: "Select one exact agent and server scope. An unavailable observation is not empty or healthy coverage.",
  "observation.observed": "Observed at the recorded time",
  "observation.held": "Coverage held",
  observationHint: "Only these resolved people were observed. No group grant, role grant or future schedule coverage is implied.",
  partial: "Partial scan",
  invalidCases: "Invalid cases in the scan",
  yes: "Yes",
  no: "No",
  heldReasons: "Recorded hold reasons",
  observationEvidence: "Observation provenance",
  "issue.catalog": "Load the complete server catalog.",
  "issue.catalog_expired": "Refresh the expired or future-dated catalog observation.",
  "issue.source_revision": "Use the complete current catalog revision, without shortening it.",
  "issue.bindings": "Keep between 1 and 30 declarations.",
  "issue.agent": "Select an exact Pantheon agent.",
  "issue.scope": "Select an exact scope from the current server catalog.",
  "issue.subject": "Use a nonblank lowercase ASCII reference, without spaces, up to 256 characters.",
  "issue.duty": "Select primary, backup or escalation.",
  "issue.utc_time": "Enter a real, explicit UTC timestamp ending in Z or +00:00.",
  "issue.interval": "The exclusive end must be later than the start.",
  "issue.expired_binding": "The declaration must not already be expired.",
  "issue.fallback": "Only a schedule may have a fallback, and it must name one distinct normalized user.",
  "issue.overlap": "The same subject, agent and scope cannot have overlapping windows, even for different duties.",
  "issue.supersedes": "Use an exact lowercase Core UUID or leave the field empty.",
  "issue.justification": "Provide a justification of 20-2000 characters excluding outer whitespace.",
  "issue.size": "Shorten the request to fit the bounded request payload; no declaration will be truncated.",
  "control.owner": "Only a server-authorized Owner can request this change.",
  "control.identity": "The current server principal is unavailable.",
  "control.awaiting_core": "A materialized Core case is required for the next command.",
  "control.catalog": "Refresh the current catalog before requesting a transition.",
  "control.source_revision": "This case no longer matches the catalog. Recover through a new reviewed draft, not an edited approval.",
  "control.requester": "Only the original requester can submit this draft.",
  "control.future": "No declaration is currently effective. Future declarations remain drafts; expired declarations require a new request.",
  "control.separation": "The requester cannot review their own case.",
  "control.already_reviewed": "This principal already reviewed the plan. A different current Owner must provide the next review.",
  "control.target": "A declared or resolved target or fallback cannot review this plan.",
  "control.terminal": "This case has no available Console transition. Artifact delivery and independent observation are separate.",
  "error.invalid_input": "The request does not match the scoped-duty contract. Correct the fields before retrying.",
  "error.unauthorized": "Authentication is unavailable. Sign in again and refresh this case.",
  "error.denied": "The server denied access. Current Owner permission and independent identity are required.",
  "error.not_found": "The exact case or source was not found. Confirm its identifier and deployment.",
  "error.conflict": "The revision or retained request conflicts with server state. Refresh the exact case before proceeding.",
  "error.unavailable": "The scoped-duty source or request binding is unavailable. No coverage or transition is inferred.",
  "error.timeout": "The bounded request timed out. Its outcome is uncertain; refresh or retry the unchanged request.",
  "error.network": "The request failed. Its outcome is uncertain; no automatic retry was made.",
  "error.malformed": "The server response is inconsistent with the exact scoped-duty contract. It was not accepted.",
  "error.cancelled": "The request was interrupted. Its outcome is not confirmed; recover using the exact case or unchanged request.",
} as const;

const KO: Record<keyof typeof EN, string> = {
  title: "범위별 담당 체계",
  subtitle: "개인 할당과 별도로, 정확한 에이전트와 범위 및 유효 기간에 대한 담당 변경을 제안합니다.",
  boundary: "담당 체계 검토 전용입니다. IAM 역할, 그룹 구성원 자격, 전역 담당 맵 변경 또는 실행 권한을 부여하지 않습니다.",
  ownerOnly: "범위별 담당 체계를 읽거나 제안하려면 서버에서 확인된 Owner 권한이 필요합니다.",
  catalog: "허용 범위 카탈로그",
  refreshCatalog: "카탈로그 새로 고침",
  sourceRevision: "전체 원본 개정 식별자",
  observedAt: "관찰 시각(UTC)",
  expiresAt: "만료 시각(UTC)",
  expired: "더 이상 유효한 관찰이 아닙니다. 계속하기 전에 원본을 새로 고치세요.",
  deliveryAvailable: "검토 산출물을 전달할 수 있습니다. 전달 가능 상태가 승인이나 병합을 의미하지는 않습니다.",
  deliveryUnavailable: "검토 산출물을 전달할 수 없습니다. 초안이나 검토만으로 담당 변경이 적용되지는 않습니다.",
  useCatalog: "이 카탈로그 개정으로 초안 변경",
  sourceChanged: "초안에 다른 카탈로그 개정이 고정되어 있습니다. 이 개정을 적용하면 초안과 재시도 식별자가 변경됩니다.",
  createTitle: "범위별 담당 초안",
  createHint: "선언을 1-30개 추가하세요. Core가 현재 담당자를 확인하고 담당 공백을 검사합니다. 선언 자체는 담당 근거가 아닙니다.",
  binding: "선언 {number}",
  addBinding: "선언 추가",
  removeBinding: "선언 {number} 삭제",
  agent: "에이전트",
  scope: "정확한 범위",
  chooseScope: "서버에서 제공한 범위 선택",
  scopeUnlisted: "현재 카탈로그에 없음",
  kind: "주체 유형",
  "kind.user": "사용자",
  "kind.group": "그룹",
  "kind.schedule": "구성된 당번 일정",
  subjectRef: "정규화된 정확한 주체 참조",
  subjectHint: "사용자나 그룹의 소문자 디렉터리 개체 ID 또는 구성된 당번 참조를 입력하세요. 이름이나 검색어는 사용할 수 없습니다.",
  duty: "담당 유형",
  "duty.primary": "주 담당",
  "duty.backup": "백업",
  "duty.escalation": "에스컬레이션",
  effectiveFrom: "유효 시작 시각(UTC)",
  effectiveUntil: "유효 종료 시각(UTC, 해당 시각 제외)",
  timeHint: "UTC 시각을 YYYY-MM-DDTHH:mm:ssZ 형식으로 입력하세요. 현재 관찰로 미래의 담당 공백 해소를 입증할 수는 없습니다.",
  fallback: "고정 대체 사용자 참조",
  fallbackHint: "모든 당번 일정에는 별도의 고정 대체 사용자가 필요합니다. 서버가 이 사용자를 독립적으로 확인하며, 두 번째 담당으로 계산하지 않습니다.",
  supersedes: "대체할 Core 사례 UUID(선택 사항)",
  supersedesHint: "동일한 에이전트와 범위의 검토된 이전 사례 하나를 대체합니다. Operator 요청 ID가 아닌 정확한 Core UUID를 입력하세요. 승인 이력은 수정하지 않습니다.",
  justification: "변경 사유(20-2000자)",
  noSecrets: "자격 증명이나 비밀을 입력하지 마세요. 초안과 재시도 요청은 메모리에만 유지되며, 페이지를 새로 고치면 전송하지 않은 입력이 사라집니다.",
  create: "초안 생성 요청",
  retryCreate: "변경 없이 생성 재시도",
  validation: "수정할 항목",
  bindingIssue: "선언 {number}: {message}",
  createUncertain: "요청이 서버에 도달했을 수 있습니다. 변경 없이 재시도하면 사례 ID를 복구할 수 있습니다. 내용을 수정하면 별도 요청이 시작됩니다.",
  accepted: "요청이 접수되어 Core 처리를 기다리고 있습니다. 상태 전이나 담당 변경은 확인되지 않았습니다. 정확한 사례를 열어 수동으로 새로 고치세요.",
  busy: "담당 체계 검토 요청을 보내는 중",
  caseTitle: "정확한 범위별 사례 열기",
  caseHint: "사례 목록이나 자동 폴링은 없습니다. 수동 새로 고침과 페이지 재접속 후 복구를 위해 사례 링크를 보관하세요.",
  caseId: "Operator 사례 ID",
  openCase: "사례 열기",
  refreshCase: "사례 새로 고침",
  caseEmpty: "정확한 operator- 사례 ID를 입력하면 서버의 현재 상태를 읽을 수 있습니다.",
  caseLink: "이 사례의 직접 링크",
  invalidCaseId: "operator- 다음에 소문자 16진수 32자를 정확히 입력하세요.",
  revision: "Core 개정 번호",
  coreCaseId: "Core 사례 UUID",
  requester: "요청자 참조",
  state: "서버에서 확인한 사례 상태",
  "state.awaiting_core": "Core 처리 대기",
  "state.draft": "초안",
  "state.pending_review": "독립 검토 대기",
  "state.approved": "검토 2건 기록됨",
  "state.ownership_pr_open": "담당 체계 검토 PR 열림",
  "state.ownership_merged": "담당 체계 병합 기록됨",
  "state.rejected": "거부됨",
  awaitingCase: "Core가 아직 요청을 사례로 반영하지 않았습니다. 개정 번호나 후속 명령을 사용할 수 없습니다.",
  retainedEvidence: "보존된 요청 및 계획 근거",
  planAt: "계획 확인 시각(UTC)",
  planDigest: "보존된 계획의 정확한 다이제스트",
  planObserved: "담당 체계는 계획 확인 시점에 관찰된 결과이며 전체 유효 기간에 대한 보장은 아닙니다.",
  planHeld: "보존된 계획에는 현재 담당 공백이 있습니다. 제출 전에 Core가 현재 원본을 확인해야 합니다.",
  planHistoric: "사례 새로 고침은 보존된 계획의 시각을 갱신하지 않습니다. 서버는 각 명령 처리 시 원본을 다시 확인합니다.",
  reviews: "기록된 독립 검토: {count} / 2",
  reviewsHint: "현재 Owner인 서로 다른 두 사람이 필요합니다. 서버가 모든 검토자, 요청자, 대상자, 대체 사용자와 이전 사례를 다시 확인합니다. 검토 기록만으로 현재 권한을 입증할 수는 없습니다.",
  noReviews: "기록된 독립 검토가 없습니다.",
  "decision.approve": "승인",
  "decision.reject": "거부",
  submit: "현재 원본 확인 및 검토 요청",
  approve: "담당 체계 계획 승인",
  reject: "담당 체계 계획 거부",
  retryCommand: "동일한 명령 재시도",
  commandPending: "명령 결과가 아직 확인되지 않았습니다. 원래 개정 번호, 결정 및 다이제스트를 유지합니다. 수동으로 새로 고치세요. 개정 번호가 그대로라면 완료된 것으로 볼 수 없습니다.",
  pr: "검토 산출물 참조",
  candidateDigest: "산출물 다이제스트",
  merge: "독립적으로 기록된 병합 커밋",
  notRecorded: "기록되지 않음",
  observationTitle: "정확한 범위의 관찰 읽기",
  readObservation: "현재 관찰 읽기",
  observationEmpty: "정확한 에이전트와 서버 범위를 하나씩 선택하세요. 관찰을 사용할 수 없다고 해서 담당자가 없거나 담당 공백이 해소되었다는 뜻은 아닙니다.",
  "observation.observed": "기록된 시각에 관찰됨",
  "observation.held": "담당 체계 확인 보류",
  observationHint: "여기에 표시된 사람만 확인되었습니다. 그룹이나 역할에 대한 권한 또는 미래 당번의 담당 범위를 의미하지 않습니다.",
  partial: "부분 조회",
  invalidCases: "조회에서 발견된 잘못된 사례 수",
  yes: "예",
  no: "아니요",
  heldReasons: "기록된 보류 사유",
  observationEvidence: "관찰 출처",
  "issue.catalog": "서버의 전체 카탈로그를 불러오세요.",
  "issue.catalog_expired": "만료되었거나 미래 시각인 카탈로그 관찰을 새로 고치세요.",
  "issue.source_revision": "줄이지 않은 현재 카탈로그 개정 식별자 전체를 사용하세요.",
  "issue.bindings": "선언 수를 1-30개로 유지하세요.",
  "issue.agent": "정확한 Pantheon 에이전트를 선택하세요.",
  "issue.scope": "현재 서버 카탈로그의 정확한 범위를 선택하세요.",
  "issue.subject": "공백 없이 소문자 ASCII 참조를 1-256자로 입력하세요.",
  "issue.duty": "주 담당, 백업 또는 에스컬레이션을 선택하세요.",
  "issue.utc_time": "Z 또는 +00:00으로 끝나는 유효한 UTC 시각을 입력하세요.",
  "issue.interval": "제외되는 종료 시각은 시작 시각보다 뒤여야 합니다.",
  "issue.expired_binding": "이미 만료된 선언은 사용할 수 없습니다.",
  "issue.fallback": "당번 일정에만 대체 사용자를 지정할 수 있으며, 별도의 정규화된 사용자 한 명이어야 합니다.",
  "issue.overlap": "같은 주체, 에이전트 및 범위의 유효 기간은 담당 유형이 달라도 겹칠 수 없습니다.",
  "issue.supersedes": "정확한 소문자 Core UUID를 입력하거나 비워 두세요.",
  "issue.justification": "앞뒤 공백을 제외하고 변경 사유를 20-2000자로 입력하세요.",
  "issue.size": "요청 크기 제한에 맞게 내용을 줄이세요. 선언을 임의로 잘라 보내지 않습니다.",
  "control.owner": "서버에서 허용한 Owner만 변경을 요청할 수 있습니다.",
  "control.identity": "현재 서버 주체를 확인할 수 없습니다.",
  "control.awaiting_core": "다음 명령에는 Core에 반영된 사례가 필요합니다.",
  "control.catalog": "상태 전이를 요청하기 전에 현재 카탈로그를 새로 고치세요.",
  "control.source_revision": "이 사례는 현재 카탈로그와 일치하지 않습니다. 승인을 수정하지 말고 새 초안을 검토하여 복구하세요.",
  "control.requester": "원래 요청자만 이 초안을 제출할 수 있습니다.",
  "control.future": "현재 유효한 선언이 없습니다. 미래 선언은 초안으로 유지되며, 만료된 선언은 새 요청이 필요합니다.",
  "control.separation": "요청자는 자신의 사례를 검토할 수 없습니다.",
  "control.already_reviewed": "이 주체는 이미 계획을 검토했습니다. 다른 현재 Owner가 다음 검토를 수행해야 합니다.",
  "control.target": "선언되었거나 확인된 대상자 및 대체 사용자는 이 계획을 검토할 수 없습니다.",
  "control.terminal": "이 사례에는 Console에서 수행할 다음 상태 전이가 없습니다. 산출물 전달과 독립 관찰은 별도 절차입니다.",
  "error.invalid_input": "요청이 범위별 담당 계약과 일치하지 않습니다. 항목을 수정한 뒤 재시도하세요.",
  "error.unauthorized": "인증을 사용할 수 없습니다. 다시 로그인한 뒤 사례를 새로 고치세요.",
  "error.denied": "서버가 접근을 거부했습니다. 현재 Owner 권한과 독립된 신원이 필요합니다.",
  "error.not_found": "정확한 사례 또는 원본을 찾지 못했습니다. 식별자와 배포를 확인하세요.",
  "error.conflict": "개정 번호나 보존된 요청이 서버 상태와 충돌합니다. 정확한 사례를 새로 고친 뒤 진행하세요.",
  "error.unavailable": "범위별 담당 원본 또는 요청 연결을 사용할 수 없습니다. 담당 체계나 상태 전이를 추정하지 않습니다.",
  "error.timeout": "요청 제한 시간이 지났습니다. 결과가 불확실하므로 새로 고치거나 같은 요청을 변경 없이 재시도하세요.",
  "error.network": "요청에 실패했습니다. 결과가 불확실하며 자동으로 재시도하지 않았습니다.",
  "error.malformed": "서버 응답이 정확한 범위별 담당 계약과 일치하지 않아 반영하지 않았습니다.",
  "error.cancelled": "요청이 중단되어 결과가 확인되지 않았습니다. 정확한 사례 또는 변경하지 않은 요청으로 복구하세요.",
};

export type ScopedDutyCopyKey = keyof typeof EN;

/** English fallback follows the existing ownership-copy pattern without shared catalog edits. */
export function scopedDutyText(key: ScopedDutyCopyKey, params?: Readonly<Record<string, string | number>>): string {
  const template = getLocale() === "ko" ? KO[key] || EN[key] : EN[key];
  return params === undefined ? template : template.replace(/\{(\w+)\}/g,
    (whole, name: string) => name in params ? String(params[name]) : whole);
}
