schema_version: 1.0.0
id: azure-builtin.compute.vm.deprecated-audit-windows-virtual-machines-on-which-the-windows-guest-configuration-extension-is-not
version: 2.0.0
source: azure_policy
severity: medium
category: compliance
resource_type: compute.vm
check_logic:
  kind: expression
  reference: azure-policy://5fc23db3-dd4d-4c56-bcc7-43626243e601
remediation:
  template_ref: remediation/azure-builtin/5fc23db3-dd4d-4c56-bcc7-43626243e601.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: 5fc23db3-dd4d-4c56-bcc7-43626243e601
  azure_policy_display_name: '[Deprecated]: Audit Windows virtual machines on which
    the Windows Guest Configuration extension is not enabled'
  azure_policy_effect_default: AuditIfNotExists
  azure_policy_category: Guest Configuration
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/Guest
    Configuration/AuditExtensionWindows_Prerequisite.json
  source_version: 2.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:04Z'
