"""Generate the mock ontology topology from the authoritative projection builder."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml
from fdai.agents import PANTHEON_SPECS
from fdai.delivery.ontology_console_projection import build_catalog_topology
from fdai.rule_catalog.schema.ontology_catalog import load_ontology_catalog
from fdai.shared.contracts.registry import PackageResourceSchemaRegistry

REPO_ROOT = Path(__file__).resolve().parents[3]
CATALOG_ROOT = REPO_ROOT / "rule-catalog"
MOCK_OUTPUT = REPO_ROOT / "mocks" / "ui" / "assets" / "ontology-knowledge-data.js"


def load_yaml_files(root: Path) -> list[dict[str, Any]]:
    """Load deterministic mock inputs that canonical loaders validate separately."""

    return [
        yaml.safe_load(path.read_text(encoding="utf-8")) for path in sorted(root.glob("*.yaml"))
    ]


def build() -> dict[str, Any]:
    """Build the same exact-release topology used by the Operator projection."""

    catalog = load_ontology_catalog(
        CATALOG_ROOT,
        schema_registry=PackageResourceSchemaRegistry(),
        probes_root=CATALOG_ROOT / "probes",
    )
    rules = load_yaml_files(CATALOG_ROOT / "catalog")
    workflows = load_yaml_files(CATALOG_ROOT / "workflows")
    resource_types = yaml.safe_load(
        (CATALOG_ROOT / "vocabulary" / "resource-types.yaml").read_text(encoding="utf-8")
    )["types"]
    agents = [
        {
            "name": spec.name,
            "layer": spec.layer.value,
            "reports_to": spec.reports_to,
            "owns": sorted(spec.owns),
            "actions": sorted(set(spec.executes) | set(spec.initiates)),
        }
        for spec in PANTHEON_SPECS
    ]
    return build_catalog_topology(
        ontology=catalog,
        resource_types=resource_types,
        rules=rules,
        workflows=workflows,
        agents=agents,
    )


def main() -> None:
    """Write the mock artifact from one authoritative deterministic graph."""

    graph = build()
    payload = json.dumps(graph, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    MOCK_OUTPUT.write_text(
        "/* Generated by mocks/ui/scripts/generate-ontology-knowledge-graph.py. */\n"
        f"window.FDAI_ONTOLOGY_KNOWLEDGE_GRAPH = Object.freeze({payload});\n",
        encoding="utf-8",
    )
    print(f"wrote {MOCK_OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
