schema_version: 1.0.0
id: azure-builtin.azure.web.sites.config.deprecated-app-service-should-disable-public-network-access
version: 1.0.0
source: azure_policy
severity: medium
category: security
resource_type: azure.web.sites.config
check_logic:
  kind: expression
  reference: azure-policy://d79ab062-dffd-4318-8344-f70de714c0bc
remediation:
  template_ref: remediation/azure-builtin/d79ab062-dffd-4318-8344-f70de714c0bc.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: d79ab062-dffd-4318-8344-f70de714c0bc
  azure_policy_display_name: '[Deprecated]: App Service should disable public network
    access'
  azure_policy_effect_default: Audit
  azure_policy_category: App Service
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/App
    Service/App_PrivateEndpoint_Audit_Deprecated.json
  source_version: 1.0.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
