schema_version: 1.0.0
id: azure-builtin.azure.web.sites.slots.configure-function-app-slots-to-use-the-latest-tls-version
version: 1.4.0
source: azure_policy
severity: medium
category: security
resource_type: azure.web.sites.slots
check_logic:
  kind: expression
  reference: azure-policy://fa3a6357-c6d6-4120-8429-855577ec0063
remediation:
  template_ref: remediation/azure-builtin/fa3a6357-c6d6-4120-8429-855577ec0063.md
remediates: remediate.azure-policy-managed
parameters:
  azure_policy_name: fa3a6357-c6d6-4120-8429-855577ec0063
  azure_policy_display_name: Configure Function app slots to use the latest TLS version
  azure_policy_effect_default: DeployIfNotExists
  azure_policy_category: App Service
provenance:
  source_url: https://github.com/Azure/azure-policy/blob/main/built-in-policies/App
    Service/RequireLatestTls_FunctionApp_Slot_DINE.json
  source_version: 1.4.0
  resolved_ref: d315bc3b9c8a382e540add3562fff4a82e027635
  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000
  license: MIT
  redistribution: embeddable
  retrieved_at: '2026-07-07T14:26:03Z'
